- index.html
- js/id/actions/copy_entity.js
- js/id/behavior/copy.js
- js/id/behavior/paste.js
- js/id/core/entity.js
- js/id/core/relation.js
- js/id/core/way.js
- js/id/id.js
- js/id/modes/browse.js
- js/id/modes/select.js
- test/index.html
- test/index_packaged.html
- test/spec/actions/copy_entity.js
- test/spec/core/entity.js
- test/spec/core/relation.js
- test/spec/core/way.js
This is for #642 
(these commits were split off from #2489)
Foundation and tests for entity copy/paste is there, need to add:
> Copy paste features

- css/app.css
> add rounded tooltips

- data/core.yaml
Changes core.yaml to fix #2504
> fixes issue #2504

- data/presets.yaml
- data/presets/presets/place/farm.json
- data/taginfo.json
Place=farm has over 26 thousand entries so far
> Added farm as preset for Place

- index.html
- js/id/actions/revert.js
- js/id/core/graph.js
- js/id/modes/save.js
- js/id/renderer/map.js
- js/id/ui/conflicts.js
- test/index.html
- test/index_packaged.html
- test/spec/actions/revert.js
- test/spec/core/graph.js
see [#537](https://github.com/openstreetmap/iD/issues/537#issuecomment-96315941)
I did not create an operation for it, but may be useful later.  For now I just want it for conflict resolution.
This seems ok to me..
@jfirebaugh @tmcw see any issues?
> Add ability to revert entity back to base version

- Makefile
- css/app.css
- data/core.yaml
- dist/locales/en.json
- index.html
- js/id/ui.js
- js/id/ui/info.js
- js/lib/d3.v3.js
This adds an information widget with some info about the selected items and distance/area measurement capability per #2519 
* Show/hide with 'i' key
* Toggles metric/imperial
cc @aaronlidman @jfirebaugh
> Infobox / distance measurement

- css/map.css
- js/id/renderer/mapillary_layer.js
In my opinion, the markers used for layer mapillary are ugly.
With this pull request, the styling is a bit better, well I hope.
Before
After
> Better look for mapillary markers

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/recycling/type.json
- data/presets/presets.json
- data/presets/presets/amenity/recycling.json
- dist/locales/en.json
> Add recycling_type preset field

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/highway/corridor.json
- dist/locales/en.json
“Hallway” in particular would be more accessible to American English speakers than “corridor”.
ref #2687
> Additional terms for corridor

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/military/checkpoint.json
- data/presets/presets/military/danger_area.json
- data/presets/presets/military/naval_base.json
- data/presets/presets/military/obstacle_course.json
- data/presets/presets/military/training_area.json
- data/taginfo.json
- dist/locales/en.json
Fix bug #2177 by adding military presets.
I hope I have changed the necessary files.
> Add military presets (fixes #2177)

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/leisure/pitch/rugby_league.json
- data/presets/presets/leisure/pitch/rugby_union.json
- data/taginfo.json
- dist/locales/en.json
- dist/locales/fr.json
I used American football icon for yet since Maki has not (yet?) one - I think it better fits rugby than standard pitch icon but that's subjective so let me know if I should change that.
> preset: add rugby_union and rubgy_league

- js/id/ui/map_in_map.js
Refs https://github.com/openstreetmap/iD/issues/2813
> Support for multiple overlays in minimap + fix for #2813

- css/app.css
- css/map.css
- dist/index.html
- img
- index.html
- js/id/id.js
- js/id/svg/defs.js
- js/id/svg/lines.js
Created a branch for tracking these items as I fix them.
see #1431, #1908 
Note: oneway markers issues see [this](http://stackoverflow.com/questions/15588478/internet-explorer-10-not-showing-svg-path-d3-js-graph)
> Support Internet Explorer 11

- data/presets/presets/amenity/vending_machine/cigarettes.json
- data/presets/presets/amenity/vending_machine/condoms.json
- data/presets/presets/amenity/vending_machine/drinks.json
- data/presets/presets/amenity/vending_machine/excrement_bags.json
- data/presets/presets/amenity/vending_machine/news_papers.json
- data/presets/presets/amenity/vending_machine/parcel_pickup_dropoff.json
- data/presets/presets/amenity/vending_machine/parking_tickets.json
- data/presets/presets/amenity/vending_machine/sweets.json
This is a pull request regarding Issue #2827.
> New presets for the different types of vending machines

- css/map.css
- index.html
- js/id/behavior/breathe.js
- js/id/modes/select.js
- test/index.html
This adds an opacity/stroke interpolator behavior which should make it a lot easier for users with colorblindness to see when things have been selected..
(closes #1814)
merging over the weekend if no opposition..
> Add Breathe behavior for interpolated select halos

- data/presets/fields/diaper.json
- data/presets/presets/amenity/toilets.json
http://wiki.openstreetmap.org/wiki/Key%3Adiaper
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets
> added diaper to amenity=toilets

- data/presets/presets/amenity/waste_disposal.json
- data/presets/presets/man_made/chimney.json
- data/presets/presets/man_made/gasometer.json
- data/presets/presets/man_made/groyne.json
- data/presets/presets/man_made/surveillance.json
- data/presets/presets/man_made/works.json
Adding presets according to issue #2893
> Adding presets according to issue #2893

- js/id/ui/entity_editor.js
In ref to
https://github.com/openstreetmap/iD/issues/2892
> Removal of faulty regex

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/shop/storage_rental.json
- data/taginfo.json
- dist/locales/en.json
Ref: https://github.com/openstreetmap/iD/issues/2943
> Addition of Storage Unit preset

- .travis.yml
- CONTRIBUTING.md
- js/id/renderer/background.js
- package.json
- test/index.html
- test/index_packaged.html
- test/spec/modes/add_point.js
> Test with phantomjs 2.1 and mocha-phantomjs-core

- CONTRIBUTING.md
I often use `live-server` while working on iD and thought it might be use for others as well.
Let me know if it is necessary 🙃
> Live reload documentation

- data/presets.yaml
- data/presets/categories.json
- data/presets/categories/building.json
- data/presets/categories/golf.json
- data/presets/categories/landuse.json
- data/presets/categories/path.json
- data/presets/categories/rail.json
- data/presets/categories/restriction.json
- data/presets/categories/road.json
- data/presets/categories/route.json
- data/presets/categories/water-area.json
- data/presets/categories/water-line.json
- dist/locales/en.json
- js/id/ui/preset_list.js
> Adding ▶/▼ to category presets to make it clearer

- CONTRIBUTING.md
The list inside live reload incorrectly displays the list in a single paragraph
> Incorrect list display in CONTRIBUTION.md

- data/presets/presets/shop/art.json
fixes https://github.com/openstreetmap/iD/issues/2999
> Change prefix name Art Gallery->Art Shop

- js/id/behavior/lasso.js
- js/id/ui/lasso.js
Allows iD to draw freeform lasso shapes
(closes #2937)
> Freeform lasso shapes

- RELEASING.md
cc @bhousel for the review. This makes the RELEASING.md doc specific about the requirement of transifex.auth
> Be explicit about Transifex requirement for release. Fixes #2900

- js/lib/d3.combobox.js
> Fix greediness of autocompletion

- js/id/behavior/draw.js
- js/id/behavior/draw_way.js
This makes the space bar function like a mouse click when drawing a way. When drawing long ways like roads it is so much more efficient because you don't have the mouse click stopping the motion of your mouse.
> Added space bar "click" when drawing ways

- css/app.css
- js/id/ui/save.js
Save button background color gradually changes as more changes are done by user.This warns user to save changes.
> save button alerts user to save changes.

- Makefile
- js/lib/d3.v3.js
> D3 mousewheeled fix

- Makefile
- index.html
- js/lib/id/core.js
- modules/core/connection.js
- modules/core/difference.js
- modules/core/entity.js
- modules/core/graph.js
- modules/core/history.js
- modules/core/index.js
- modules/core/node.js
- modules/core/relation.js
- modules/core/tags.js
- modules/core/tree.js
- modules/core/way.js
- test/index.html
> Modularize iD.core

- Makefile
- index.html
- js/lib/id/geo.js
- js/lib/id/index.js
- js/lib/id/ui/intro.js
- modules/actions/add_member.js
- modules/actions/add_midpoint.js
- modules/actions/circularize.js
- modules/actions/disconnect.js
- modules/actions/join.js
- modules/actions/merge_polygon.js
- modules/actions/merge_remote_changes.js
- modules/actions/move.js
- modules/actions/orthogonalize.js
- modules/actions/restrict_turn.js
- modules/actions/split.js
- modules/core/connection.js
- modules/core/graph.js
- modules/core/history.js
- modules/core/node.js
- modules/core/relation.js
- modules/core/way.js
- modules/geo/intersection.js
- modules/index.js
- replaceStuff.js
- test/index.html
After a discussion with @bhousel, we decided it would be a better idea for all of us to do phase 2 in steps.
I ran tests locally and will continue to do more ui testing on browser.
cc: @tmcw
> Ext modules for core, actions, geo

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/man_made/bridge.json
- data/taginfo.json
- dist/locales/en.json
add man_made=bridge to presets #3183
> Adding man_made=bridge preset issue# 3183

- data/presets.yaml
- data/presets/fields.json
- data/presets/presets.json
- data/presets/presets/emergency/defibrillator.json
- data/taginfo.json
- dist/locales/en.json
Added `emergency =defibrillator` to the preset list to fix #3202.
> Adding emergency =defibrillator preset (fixes #3202)

- .eslintrc
- Makefile
- index.html
- js/lib/id/index.js
- modules/core/connection.js
- modules/modes/save.js
- modules/util/jxon.js
- test/index.html
* Q: why not the jxon module?
* A: We're using [algorithm 2](https://developer.mozilla.org/en-US/docs/Archive/JXON#Usage), which has a `@` shorthand.
> Use local jxon

- Makefile
- index.html
- js/lib/id/services.js
- modules/index.js
- modules/services/index.js
- modules/services/mapillary.js
- modules/services/nominatim.js
- modules/services/taginfo.js
- modules/services/wikidata.js
- modules/services/wikipedia.js
- modules/svg/mapillary_images.js
- modules/svg/mapillary_signs.js
- modules/ui/fields/address.js
- modules/ui/fields/input.js
- modules/ui/fields/localized.js
- modules/ui/fields/wikipedia.js
- test/index.html
- test/spec/services/mapillary.js
- test/spec/services/nominatim.js
- test/spec/services/taginfo.js
- test/spec/ui/fields/wikipedia.js
TBD issues with 
* wrapping closure module in `init()` function
* Wikipedia field tests failing because `sinon.stub` can't stub the wikidata lookup function
> External modules for services

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/amenity/ice_cream.json
- data/taginfo.json
- dist/locales/en.json
> create amenity = ice_cream issue #3253

- data/address-formats.json
Sorry. I forget a comma in #3260, so I pull request again.
> Add Taiwan (R.O.C.) address format

- modules/core/connection.js
> fix critical error on save changes

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/amenity/planetarium.json
- data/taginfo.json
- dist/locales/en.json
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dplanetarium
> Add preset for amenity=planetarium

- css/app.css
- modules/ui/selection_list.js
> Remove an item from the multiselect list

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/blood_components.json
- data/presets/presets.json
- data/presets/presets/healthcare/blood_donation.json
- data/taginfo.json
- dist/locales/en.json
Preset for [healthcare=blood_donation](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dblood_donation) :heart::droplet:, as promised in #3285.
I didn't even think about adding the part about which compensation you receive, because we already had problems enough with the blood components. :stuck_out_tongue:
Some mini golf changes ended up here as well, due to executing `make`.
> Preset for blood donor centers

- css/app.css
- modules/ui/selection_list.js
Includes splitting select/deselect elements into separate buttons, fixes issue brought up in #3275
> Fix deselect entity on Firefox

- test/spec/services/taginfo.js
Added a test for #3280, per https://github.com/openstreetmap/iD/pull/3280#issuecomment-236330422.
/cc @bhousel
> Test uppercase network suggestions

- modules/ui/fields/maxspeed.js
75 and 80 mph speed limits are [common in several U.S. states](https://en.wikipedia.org/wiki/Speed_limits_in_the_United_States).
> Add 75, 80 mph speed limits

- .eslintrc
- build.js
- data/presets/presets.json
- modules/actions/deprecate_tags.js
- modules/actions/discard_tags.js
- modules/actions/merge_remote_changes.js
- modules/core/context.js
- modules/core/entity.js
- modules/core/graph.js
- modules/index.js
- modules/services/taginfo.js
- modules/svg/debug.js
- modules/svg/mapillary_images.js
- modules/svg/mapillary_signs.js
- modules/svg/tag_classes.js
- modules/ui/fields/address.js
- modules/ui/fields/combo.js
- modules/ui/fields/input.js
- modules/ui/fields/localized.js
- modules/ui/fields/maxspeed.js
- modules/ui/fields/wikipedia.js
- modules/ui/preset_icon.js
- package.json
> Remove continued iD references

- data/presets/presets/leisure/pitch/bowls.json
Came across many bowling greens in the UK but there's no preset.
> Add Bowling Green preset

- data/presets/presets/leisure/fitness_centre/yoga.json
Hi,
I've added a preset for Yoga Studio as mentioned in issue #3352.  Would you like to check it for inclusion from my branch?
Thanks!
Jon
> Add Yoga Studio preset #3352

- data/presets/presets.json
- data/presets/presets/leisure/garden.json
- data/presets/presets/leisure/pitch/basketball.json
- data/presets/presets/leisure/pitch/tennis.json
Hi,
I've added access_simple tags to basketball, tennis courts & garden as requested in #3336 - please can you review my changes?
Thanks,
Jon
> Add access_simple field to basketball, tennis & garden presets (#3336)

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/man_made/pumping_station.json
- data/taginfo.json
- dist/locales/en.json
> Add preset man_made=pumping_station

- CONTRIBUTING.md
- README.md
This updates the readme to reflect recent changes in the project structure.
> update installation instructions and prerequisites

- data/presets/presets/man_made/surveillance.json
Thanks for the advice, I seem to have got the hang of github now :)
> Add cctv term for surveillance

- data/presets/presets/amenity/charging_station.json
Suppose there should be more fields with all the socket options etc, but this will do for now.
> Add capacity field to amenity=charging_station preset

- data/presets/presets/leisure/fitness_centre.json
- data/presets/presets/leisure/fitness_station.json
> Add indoor/outdoor gym, update sports centre presets

- data/presets/presets/railway/crossing.json
Fixes #3395 - cloned the terms from the level crossing preset
> Add railway crossing (path) and update railway crossing (road)

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/shop/pastry.json
- data/presets/presets/shop/pastry_shop.json
- data/taginfo.json
- dist/locales/en.json
> Add pastry shop preset

- data/presets/presets/shop/anime.json
Updated Anime Shop preset with anime related terms. ^_^
> Updated Anime Terms

- modules/core/way.js
- test/spec/core/way.js
This PR adds complete turn lanes parsing and test cases.
> Turn lanes: Lane editor

- modules/actions/reverse.js
- test/spec/actions/reverse.js
Hi,
I've created this pull request for an implementation to address issue #3076.  I've added some unit tests for operation and also tested it out in a local iD build and it seems to work.  Can you please review and let me know if it's ok?
Thanks!
Jon
> Reverse tags on nodes belonging to way on reversal (#3076)

- FAQ.md
> fix connection.js to osm.js in FAQ

- data/presets/fields/fire_hydrant/position.json
- data/presets/presets/emergency/fire_hydrant.json
http://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant
> Add fire_hydrant:position field to presets

- modules/actions/circularize.js
- modules/actions/orthogonalize.js
- modules/actions/reflect.js
- modules/actions/straighten.js
- modules/core/history.js
- test/spec/actions/circularize.js
- test/spec/actions/orthogonalize.js
- test/spec/actions/reflect.js
- test/spec/actions/straighten.js
- test/spec/core/history.js
see #3659 
history:
actions:
tests:
also:
> Transitioned actions

- data/presets/fields.json
- data/presets/fields/step_count.json
- data/presets/presets.json
- data/presets/presets/highway/steps.json
Solves #3716 - added the field to the bottom of the preset
> Add step_count field

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/email.json
- data/presets/fields/fax.json
- dist/locales/en.json
Fixes #3710.
I don't know if it's desirable to have fax as a universal field. Perhaps it'd be better to separately add it to more features? In that case this PR has to be modified. Otherwise: ready to merge!
> Add universal email field, make fax universal

- modules/services/index.js
- modules/services/nominatim.js
- modules/ui/feature_list.js
> Add a pluggable geocoder

- modules/core/context.js
see #3755 
This adds a special language for debugging translations.
> Add _tkeys_ language for translation debugging

- data/presets.yaml
- data/presets/categories.json
- data/presets/categories/road.json
- data/presets/presets.json
- data/presets/presets/noexit/yes.json
- data/presets/presets/shop/watches.json
- data/taginfo.json
- dist/locales/en.json
Add presets to:
* noexit=yes -> https://wiki.openstreetmap.org/wiki/Key:noexit
* shop=watches -> https://wiki.openstreetmap.org/wiki/Tag:shop%3Dwatches
and include living street prest to the road category.
> 2 new presets and add living street to Road preset category

- data/core.yaml
> Add ".." to "Uploading changes to OpenStreetMap."

- data/presets.yaml
- data/presets/categories.json
- data/presets/categories/landuse.json
- data/presets/presets.json
- data/presets/presets/landuse/aquaculture.json
- data/taginfo.json
- dist/locales/en.json
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Daquaculture
> add preset to landuse=aquaculture

- data/address-formats.json
We write provinces and cities first :)
> Add Chinese(PRC) address format

- modules/ui/fields/input.js
- modules/ui/fields/radio.js
The increment button was on the left and the decrement on the right. I inverted them position:
> invert position of increment and decrement buttons

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/leisure/pitch/soccer.json
- dist/locales/en.json
Hi,
We like to call it football instead of soccer, so I have added an extra search term to make this possible.
Thanks :+1:
> Adding "football" terms to soccer pitch

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/craft/distillery.json
- data/taginfo.json
- dist/locales/en.json
Added distillery preset, resolving #4085
> Add distillery

- data/presets/presets/power/generator.json
Make it easier for people to add wind turbines etc. - maybe better to create a proper preset for it, but getting people to the power generator preset is better than nothing.
> Add terms to power generator

- modules/renderer/background.js
Here's a quick workaround for #4162.
@bhousel I'm not sure if it's the best way to fix the issue but it seem to work.
> Remember the chosen custom background when set by url

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/manhole/telecom.json
- data/taginfo.json
- dist/locales/en.json
This adds the telecom preset
manhole=telecom
> Adding telecom preset

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/ref_aeroway.json
- data/presets/presets.json
- data/presets/presets/aeroway/aerodrome.json
- dist/locales/en.json
This fixes the latest issue in #4180
> Removing aeroway reference code

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/ref_airfield.json
- data/presets/presets.json
- data/presets/presets/landuse/military/airfield.json
- dist/locales/en.json
> Remove airfield ref

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/railway/buffer_stop.json
- data/taginfo.json
- dist/locales/en.json
This adds a buffer_Stop preset, using a lovely new icon :+1:
> Adding buffer_stop preset

- css/80_app.css
- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/bridge.json
- data/presets/fields/cutting.json
- data/presets/fields/embankment.json
- data/presets/fields/ford.json
- data/presets/fields/layer.json
- data/presets/fields/tunnel_waterway.json
- data/presets/presets.json
- data/presets/presets/waterway/ditch.json
- data/presets/presets/waterway/drain.json
- data/presets/presets/waterway/river.json
- data/presets/presets/waterway/stream.json
- dist/locales/en.json
- modules/index.js
- modules/ui/entity_editor.js
- modules/ui/field.js
- modules/ui/fields/input.js
- modules/ui/fields/radio.js
- modules/ui/index.js
- modules/ui/intro/navigation.js
- modules/ui/preset.js
- modules/ui/preset_editor.js
This is a WIP for #3914 
It doesn't change how things look, but it will let us put a field anywhere, rather than having them only exist in the preset editor.  This will cleanup some technical debt, and unblock issues where we want to show a subfield inside a field.
> Field refactor

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/amenity/social_facility/group_home.json
- data/presets/presets/amenity/social_facility/nursing_home.json
- dist/locales/en.json
- Care home now displays for group home
- Assisted living now displays group home and nursing home
#1000th PR :champagne:
> Adding some more terms to group home

- data/presets/presets.json
- data/presets/presets/emergency/defibrillator.json
> Defibrillator preset adjustment

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/duration.json
- data/presets/presets.json
- data/presets/presets/route/ferry.json
- dist/locales/en.json
add operator, duration and access fields. https://wiki.openstreetmap.org/wiki/Tag:route%3Dferry
> add more fields to Ferry Route preset

- modules/actions/reflect.js
Not all edges of the poly hull were being checked when determining hull's smallest enclosing rectangle
edit: referencing #4238
> check final edge in poly hull in reflect action

- css/45_waterways.css
- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/type/waterway.json
- data/taginfo.json
- dist/locales/en.json
> Add waterway relation preset 

- data/address-formats.json
As in #4306 I am submitting a change for Poland
> Improve address format for Poland

- data/presets/presets.json
- data/presets/presets/amenity/bicycle_repair_station.json
- data/presets/presets/amenity/charging_station.json
- data/presets/presets/amenity/waste_basket.json
- data/presets/presets/highway/footway.json
> remove area from some presets geometry

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/amenity/vending_machine/feminine_hygiene.json
- data/taginfo.json
- dist/locales/en.json
> add preset for vending=feminine_hygiene

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/amenity/vending_machine/feminine_hygiene.json
- dist/locales/en.json
Sorry, yesterday I inserted the terms for 'feminine_hygiene' wrongly
> fix feminine_hygiene terms

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/leisure/bowling_alley.json
- data/presets/presets/leisure/hackerspace.json
- data/taginfo.json
- dist/locales/en.json
https://wiki.openstreetmap.org/wiki/Talk:Tag:leisure%3Dhackerspace
> add preset for hackerspace

- css/80_app.css
- modules/ui/init.js
- modules/ui/sidebar.js
* moved uiNotice from sidebar.js to init.js 
* made couple of small styling changes on the for the notice module to play well over the map
Hope this is all on the right track. All hints, tips, critiques are very welcome for this beginner.
> Move zoom to edit notice from sidebar to map container

- data/presets/fields/memorial.json
- data/presets/presets/historic/memorial.json
Adds a dropdown for the memorial=* values.
> Add memorial type field

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/volcano/status.json
- data/presets/fields/volcano/type.json
- data/presets/presets.json
- data/presets/presets/natural/volcano.json
- dist/locales/en.json
Closes #4365 
1             |  2
:-------------------------:|:-------------------------:
> Adding volcano status and volcano type

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/craft/confectionery.json
- data/presets/presets/shop/confectionery.json
- dist/locales/en.json
> Update confectionery presets

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/highway/speed_camera.json
- data/presets/presets/man_made/surveillance.json
- data/presets/presets/man_made/surveillance_camera.json
- dist/locales/en.json
> Allow cameras on a vertex

- modules/ui/source_switch.js
Closes #4401 -- fixed as proposed in the issue's comments
> Disable source switcher during walkthrough

- data/presets/presets/shop/tiles.json
Added Tile Shop presets as part of #4410
> Added Tile Shop preset

- data/presets/fields/trade.json
- data/presets/presets/shop/trade.json
Added Trade Shop presets #4410
> Added Trade Shop presets #4410

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/substance.json
- data/presets/presets.json
- data/presets/presets/man_made/pipeline.json
- dist/locales/en.json
- add substance field to pipeline preset
https://github.com/openstreetmap/iD/issues/4430
> feat(preset): add substance field to pipeline preset

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/leisure/sauna.json
- data/taginfo.json
- dist/locales/en.json
> Add sauna preset

- modules/renderer/background.js
- modules/svg/gpx.js
> push the gpx src (file name or url) to imagery_used

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/landuse/brownfield.json
- data/presets/presets/landuse/greenfield.json
- data/taginfo.json
- dist/locales/en.json
> Add landuse=brownfield/greenfield presets

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/leisure/pitch/boules.json
- data/taginfo.json
- dist/locales/en.json
Boules preset has been added as requested in #4449
> Added "Boules" preset for leisure

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/place/islet.json
- data/taginfo.json
- dist/locales/en.json
I added a preset for islets, as requested in #4458. As I'm new to this, please let me know if I need to change anything.
> Add islet preset

- data/presets/presets.json
- data/presets/presets/waterway/drain.json
Changed icon of drain preset to the ditch icon, as requested in #4460.
> Change drain icon to ditch

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/devices.json
- data/presets/fields/frequency.json
- data/presets/fields/phases.json
- data/presets/fields/rating.json
- data/presets/fields/transformer.json
- data/presets/fields/voltage/primary.json
- data/presets/fields/voltage/secondary.json
- data/presets/fields/voltage/tertiary.json
- data/presets/fields/windings.json
- data/presets/fields/windings/configuration.json
- data/presets/presets.json
- data/presets/presets/power/transformer.json
- dist/locales/en.json
> Adding details to power transformer preset

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/fitness_station_type.json
- data/presets/presets.json
- data/presets/presets/leisure/fitness_station.json
- dist/locales/en.json
> Update fitness station preset

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/tourism/alpine_hut.json
- dist/locales/en.json
> Add "Climbing hut" term to alpine hut

- data/presets/fields.json
- data/presets/fields/source.json
> Don't add unneeded underscores to source

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/tourism/wilderness_hut.json
- data/taginfo.json
- dist/locales/en.json
> Add preset for tourism=wilderness_hut

- data/presets/presets/amenity/music_school.json
see https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmusic_school
> add preset for music schools

- data/presets/presets/craft/sculptor.json
I believe this is a fairly clear typo in the presets
> It is sculptor not sculpter

- data/presets/presets/railway/light_rail.json
adds preset for #4528
https://wiki.openstreetmap.org/wiki/Tag%3Arailway%3Dlight_rail
> added preset for railway=light_rail

- data/presets/presets/amenity/telephone.json
added common fields in telephone preset(for #4529)
https://wiki.openstreetmap.org/wiki/Tag:amenity=telephone
> added common fields for preset amenity=telephone

- data/presets/presets/railway/miniature.json
Go easy on me - first github project and pull request!
> Preset for railway=miniature

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/monitoring_multi
- data/presets/presets/man_made/monitoring_station
- dist/locales/en.json
> preset for man_made=monitoring_station

- data/core.yaml
- dist/locales/en-GB.json
- dist/locales/en.json
Three files contained an extra be, before the word also. I have removed this typo.
> Removed extra 'be' from en.json, en-GB.json, and core.yaml

- data/presets.yaml
- data/presets/fields.json
- data/presets/fields/brewery.json
- data/presets/presets.json
- data/presets/presets/amenity/bar.json
- data/presets/presets/amenity/biergarten.json
- data/presets/presets/amenity/pub.json
- dist/locales/en.json
> add a field preset for the brewery tag

- css/60_photos.css
> Lower z-index to be smaller than shaded class

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/amenity/love_hotel.json
- data/taginfo.json
- dist/locales/en.json
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlove_hotel
> add preset for amenity=love_hotel

- data/address-formats.json
> remove addr:unit field for gb, ie, si, tr

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/building/boathouse.json
- data/taginfo.json
- dist/locales/en.json
I added the boathouse preset as described by this issue:
openstreetmap/iD#4661
> Added a boathouse preset

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/emergency/water_tank.json
- data/taginfo.json
- dist/locales/en.json
I have been mapping some [water tanks](https://taginfo.openstreetmap.org/tags/emergency=water_tank) used by firefighters and I noticed iD doesn't have a preset for it, so here is one.
> Added a preset for emergency/water_tank

- data/core.yaml
- dist/locales/en.json
- modules/validations/many_deletions.js
closes #4666
Modified the warning message when deleting many entities according to the suggestion in the discussion on the issue.
> Warning on multiple deletions: added some details.

- modules/renderer/background_source.js
resolves #4766 
reference: https://www.arcgis.com/home/item.html?id=298f03f7f02c465a87bcf817c3b8859b
> query the appropriate metadata for esri clarity

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/leisure/amusement_arcade.json
- data/taginfo.json
- dist/locales/en.json
I'm not sure about the icon to use (between the dice and the video game controller)
> add amusement arcade preset (closes #4774)

- modules/svg/gpx.js
> fixes 4795 : Added check for properties

- data/presets/presets.json
- data/presets/presets/shop/beauty.json
> Corrected errors of beauty shop preset

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/highway/passing_place.json
- data/taginfo.json
- dist/locales/en.json
Added this by creating a `new passing_place.json`. On building, the yaml
and other files were automatically generated.
Refs:https://github.com/openstreetmap/iD/issues/4883
> added passing place to presets

- data/core.yaml
- dist/locales/en.json
- modules/ui/tag_reference.js
In ref to #4833.
This PR currently adds alternate text for information icon. I am still not sure if the structure of core.yaml modified by me is correct. Please let me know if it's not.
> Added alt text for information icon.

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/man_made/observatory.json
- data/taginfo.json
- dist/locales/en.json
In reference to #4855.
@bhousel Please let me know if I have missed anything.
> Added preset for man_made=observatory.

- data/core.yaml
- dist/locales/en.json
- modules/ui/field.js
> Hint text for Remove and Undo button.

- data/presets/presets.json
- data/presets/presets/amenity/fuel.json
> Add support for “brand=*” for “amenity=fuel”.

- data/presets/presets.json
- data/presets/presets/building/hotel.json
- data/presets/presets/tourism/hotel.json
> Added brand=* for hotels.

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/natural/mud.json
- data/taginfo.json
- dist/locales/en.json
Refs: https://github.com/openstreetmap/iD/issues/4923
> added mud to presets natural

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/amenity/monastery.json
- data/taginfo.json
- dist/locales/en.json
Refs:https://github.com/openstreetmap/iD/issues/4932
> added monastary

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/leisure/beach_resort.json
- data/taginfo.json
- dist/locales/en.json
Refs:https://github.com/openstreetmap/iD/issues/4955
> added beach_resort.json in leisure

- data/presets/presets.json
- data/presets/presets/leisure/pitch/american_football.json
- data/presets/presets/leisure/pitch/baseball.json
- data/presets/presets/leisure/pitch/basketball.json
- data/presets/presets/leisure/pitch/beachvolleyball.json
- data/presets/presets/leisure/pitch/boules.json
- data/presets/presets/leisure/pitch/bowls.json
- data/presets/presets/leisure/pitch/cricket.json
- data/presets/presets/leisure/pitch/equestrian.json
- data/presets/presets/leisure/pitch/rugby_league.json
- data/presets/presets/leisure/pitch/rugby_union.json
- data/presets/presets/leisure/pitch/skateboard.json
- data/presets/presets/leisure/pitch/soccer.json
- data/presets/presets/leisure/pitch/table_tennis.json
- data/presets/presets/leisure/pitch/tennis.json
- data/presets/presets/leisure/pitch/volleyball.json
> Added name for pitch preset.

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/healthcare/laboratory.json
- data/taginfo.json
- dist/locales/en.json
> healthcare=laboratory preset

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/attraction/maze.json
- data/taginfo.json
- dist/locales/en.json
> Added attraction maze

- CHANGELOG.md
- add missing link
- format list
- clarify an entry
Note: the change on the description of a buggy behavior was based on from reading  #4951 and 4041ab48f, but I might have misread something. Please confirm that it is correct.
> CHANGELOG: minor fixes

- data/presets/presets/building/grandstand.json
see https://wiki.openstreetmap.org/wiki/Tag:building%3Dgrandstand
> add preset for grandstands

- css/50_misc.css
- modules/svg/tag_classes.js
This renders piers.
Now they look like this: ![](https://i.imgur.com/MZFnwEA.png)
Closes #5061
> Render pier like railway platform

- .gitignore
- dist/locales/en.json
- test/spec/services/mapillary.js
- test/spec/services/openstreetcam.js
This should clean up #5105, however it seems that there is a localization file that was updated on build. This may need to be removed?
> removed: user mocks from image service test specs

- test/data/gpxtest.gpx
- test/data/gpxtest.json
- test/data/gpxtest.kml
- test/spec/svg/gpx.js
Hey @bhousel!! I have added some tests in the gpx.js Please check.
> Some gpx tests.

- data/presets/presets/leisure/bandstand.json
> Create preset for leisure=bandstand

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/natural/tree_row.json
- data/taginfo.json
- dist/locales/en.json
This aligns the preset's name capitalization with other multi-word preset names.
> Changes the preset name "Tree row" to "Tree Row"

- modules/modes/add_point.js
> Adding a new point on a way will add a vertex, not a standalone point

- data/presets/presets/place/city_block.json
> adds a place=city_block preset

- modules/svg/tag_classes.js
> Style unpaved Taxiway

- modules/services/taginfo.js
- test/spec/services/taginfo.js
fixes #5460 
warning: this proposed code change is not tested
> tag values with wiki page may be documented as bad

- data/presets/presets/office/religion.json
Adds presets for office=religion
> office=religion preset

- css/80_app.css
> Visually centers the change count in the save button

- modules/services/taginfo.js
- test/spec/services/taginfo.js
> Amend TagInfo API calls to use current locale

- modules/svg/areas.js
In addition to https://github.com/openstreetmap/iD/commit/3aa7dcfc0c73a1423d04d29c295379e58f15582a for https://github.com/openstreetmap/iD/issues/5562.
> Grass surface rendering for traffic calming areas

- css/80_app.css
- modules/ui/commit.js
> 5614 - add close button to commit side bar

- modules/core/context.js
- modules/ui/commit_warnings.js
- modules/validations/issueManager.js
- IssueManager performs validation on the current graph and also
stores the issues and notifies listeners when the issues changed
> added IssueManager

- modules/services/maprules.js
- test/index.html
- test/spec/services/maprules.js
- test/spec/validations/missing_tag.js
added a test around the `missing_tag` validator
also fixed tests  @gaoxm
> Wonga validation tests

- modules/ui/raw_member_editor.js
> remove highlight from relation member after it is deleted from relation

- modules/validations/crossing_ways.js
- test/spec/validations/crossing_ways.js
1. Add more way types and relation types to check
2. Add more legit crossing cases
3. Add tests for 1 and 2
> Improve cross way check

- CONTRIBUTING.md
Removes a typo in CONTRIBUTING.md
> Improves CONTRIBUTING.md

- README.md
'Large' on its own doesn't really convey any information :)
> Quantify 'large' download

- css/80_app.css
> margin-right for keyhints in rtl locale

- css/80_app.css
- modules/ui/field_help.js
fix for #5705 and second part of #5687
> fix for some rtl issues

- modules/ui/fields/input.js
> Improve number field usability

- modules/services/improveOSM.js
- modules/ui/improveOSM_comments.js
- modules/ui/improveOSM_editor.js
- modules/ui/index.js
If you want to test this out, I've left a few test comments on the oneway issue found at `&map=17.00/64.08049/-21.94070`.
Things to fix before merging:
Preview:
> Add comments to ImproveOSM issues

- modules/behavior/draw.js
- modules/behavior/draw_way.js
- modules/behavior/hover.js
- modules/modes/drag_node.js
- modules/presets/index.js
> Dont snap to non-vertices

- data/deprecated.json
> add amenity=toilet to amenity=toilets validator rule

- data/deprecated.json
https://taginfo.openstreetmap.org/tags/landuse=conservation 
idea from https://josm.openstreetmap.de/browser/josm/trunk/data/validator/deprecated.mapcss#L776
> landuse=conservation to boundary=protected_area

- data/core.yaml
- dist/locales/en.json
- modules/actions/orthogonalize.js
- modules/core/history.js
- modules/geo/index.js
- modules/geo/ortho.js
- modules/operations/circularize.js
- modules/operations/orthogonalize.js
- modules/validations/index.js
- modules/validations/unsquare_way.js
> Add validation warning for unsquare buildings

- data/deprecated.json
See https://wiki.openstreetmap.org/wiki/Key%3Aclub , club is documented as a top-level tag
> Deprecate amenity/leisure=club/social_club

- data/presets/presets/man_made/dyke.json
A "levee" in American English. Used 12k+ times, documented here:
https://wiki.openstreetmap.org/wiki/Tag:man_made=dyke
> Add man_made=dyke preset

- data/presets/presets/tourism/information/terminal.json
Used 5k+ times, see https://wiki.openstreetmap.org/wiki/Tag:information%3Dterminal
> Add tourism information terminal preset

- data/presets/presets/man_made/tower/defensive.json
See https://wiki.openstreetmap.org/wiki/Tag%3Atower%3Atype%3Ddefensive , used 3800+ times
> Add castle tower preset

- data/presets/presets/amenity/social_facility/ambulatory_care.json
The office/base of a company offering ambulatory care.
Documented here: https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dambulatory_care
Used 1000+ times.
> add ambulatory_care preset

- data/presets/presets/barrier/height_restrictor.json
Used 2200+ times, documented since 2009 (on own page since 2016)
See https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dheight_restrictor
> add height restrictor preset

- API.md
- data/core.yaml
- dist/locales/en.json
- modules/renderer/features.js
- Extract the building:part from the building filter into it's own filter
- Add indoor filtering
- Update api doc
> Add filter building:part and indoor

- package.json
Upgraded module, added a test to confirm digit passes through OK
Fixes #6679 
https://github.com/Georeactor/alif-toolkit/commit/ebfc865ed3c67a148b0b0e0eb766ec983d6f6c07
> Upgrade Arabic text shaping [fixes #6679]

- css/80_app.css
- modules/ui/background.js
- modules/ui/commit.js
- modules/ui/contributors.js
- modules/ui/geolocate.js
- modules/ui/help.js
- modules/ui/init.js
- modules/ui/issues.js
- modules/ui/map_data.js
- modules/ui/raw_member_editor.js
- modules/ui/source_switch.js
- modules/ui/tools/modes.js
- modules/ui/tools/save.js
- modules/ui/tools/sidebar_toggle.js
- modules/ui/version.js
- modules/ui/zoom.js
General/minor improvements to keyboard accessibility
- Makes more buttons and links in the main interface accessible by using the tab key
- Aligns some hover and focus styles
> Minor keyboard accessibility improvements

- data/presets/fields/stile.json
- data/presets/presets/barrier/stile.json
Attempt 2 at adding the stile and material fields to the stile preset, sans weird commit spam.
> Update stile preset (again)

- data/deprecated.json
> Added missing tags to golf

- data/deprecated.json
Added corridor to jet bridge since it's the most common combination.
> Added corridor to jet bridge

- css/80_app.css
- data/core.yaml
- dist/locales/en.json
- modules/ui/feature_info.js
- modules/ui/index.js
- modules/ui/init.js
- modules/ui/issues.js
- modules/ui/issues_info.js
- modules/ui/source_switch.js
> Add issue count badges to the bottom info bar when validating Everything

- data/presets.yaml
- data/presets/presets.json
- data/presets/presets/shop/brewing_supplies.json
- data/taginfo.json
- dist/locales/en.json
> Add brewing supply store preset

- data/core.yaml
- modules/actions/circularize.js
- modules/geo/index.js
- modules/geo/vector.js
- test/spec/actions/circularize.js
It solves issue [#6816](https://github.com/openstreetmap/iD/issues/6816).I disable circularize if it's already circular. I recognize circular object through compare distances between nodes and centroid and test if central angles are smaller than maxAngle.
> Fix issue #6816

- data/presets/presets/highway/steps.json
Adding this field in the main ones, just like for street crossings, as it is very important for accessibility and safety.
> add tactile paving to steps

- modules/ui/issues.js
It is covered by buttons (for input value 1)
> increase width of input field

- modules/services/osm.js
---
This pull request is about parsing performance, for context see https://github.com/openstreetmap/iD/issues/1727#issuecomment-26099201
---
The code in here adds parsing logic for an OSM/[Overpass based JSON](http://overpass-api.de/output_formats.html) format, which I implemented as part of https://github.com/zerebubuth/openstreetmap-cgimap/pull/153.
As the deployment of the JSON format to production is currently delayed due to missing support on the Rails port, the code in here is "silent" and inactive. To enable the new JSON parser, a few more changes would be needed:
*  loadFromAPI: 
- call to `return parseXML(payload, callback, options);` needs to be replaced by  `return parseJSON(payload, callback, options); `
- `d3_xml(url, { signal: controller.signal })` needs to be replaced by …
> OSM API /map call: support Overpass JSON format 

- data/presets/presets/emergency/landing_site.json
https://wiki.openstreetmap.org/wiki/Tag:emergency=landing_site
> add emergency=landing_site preset

- data/presets/presets/advertising/billboard.json
- data/presets/presets/advertising/board.json
- data/presets/presets/advertising/column.json
- data/presets/presets/advertising/poster_box.json
- data/presets/presets/advertising/totem.json
"Who can change the content of the board?" option added based on the Wiki page.
> Add simple access to advertising

- css/80_app.css
> Updated Waterway Icon , Fixes #6986
