data/presets.yaml
data/presets/presets.json
data/presets/presets/amenity/public_bookcase.json
data/taginfo.json
dist/locales/en.json

This commit adds support to amenity=public_bookcase, a recently approved tag:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_bookcase
Contributing to iD is actually easy. Thanks for it!

Add amenity=public_bookcase preset

---

data/presets/presets.json
data/presets/presets/highway/bus_stop.json
data/presets/presets/public_transport/platform.json
data/presets/presets/public_transport/stop_position.json
data/presets/presets/railway/station.json

There are multiple companies involved in public transport (PT), but the one which the user faces (and mostly cares about) is the *network*, and the operator is at best not clearly visible to users.
However, operator=* is often used to store the PT network name instead of network=*.
I suspect it might be caused by the ordering (and sometimes lack) of the network=* tag in presets, which this PR tries to fix.

Add/Prioritize network=* tag in public transport presets

---

css/app.css
css/map.css
index.html
js/id/ui.js
js/id/ui/map_in_map.js
test/index.html

* press 'M' to toggle
* shows current zoom - 6
* with locator overlay and bounding box
Pretty sweet!
@aaronlidman

Map-in-Map overview box

---

js/id/core/connection.js
js/id/id.js

This adds some simple info to the changeset tags about browser and platform used.
Reporting this info is useful for some things (see #2449).
* Browser version is detected as major.minor only (no patch included).
* Platform is very simple (Windows/Macintosh/Linux) with no version.
* These fields are namespaced with 'iD:' to not conflict anything
Looks like this in practice:
cc @pnorman

Add basic browser and platform into to changeset tags

---

js/id/actions/move.js
js/id/core/history.js
js/id/geo.js
js/id/geo/extent.js
js/id/id.js
js/id/modes/move.js
test/spec/core/history.js
test/spec/geo/extent.js

The simple case wasn't too bad:
These get tricker, handling endpoints, closed ways, etc
I'm mostly happy with how it works, may make a few improvements before merging.

Avoid zorroing connected ways when moving a way

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/man_made/mast.json
data/taginfo.json
dist/locales/en.json

This PR adds a preset for `man_made=mast` called “radio mast”, along with various synonyms. OSM’s distinction between masts, towers, and communication towers is a bit idiosyncratic, but `man_made=mast` is [appropriate for most communications towers and guyed broadcast towers](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmast#First_question:_Is_it_a_mast_or_a_tower.3F).
/cc @gregcrago

Radio mast preset

---

build.js

validatePresetFields() tested old fields from file, not newly aggregated ones.

fix: build.js tests wrong fields in validatePresetFields()

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/man_made/petroleum_well.json
dist/locales/en.json

This PR adds a preset for [`man_made=petroleum_well`](http://taginfo.openstreetmap.org/tags/man_made=petroleum_well) called “oil well”, along with various synonyms. It uses the existing oil well icon.
@gregcrago also asked for a way to tag oil fields – areas where one can find many of derricks or pumpjacks. Unfortunately, there [doesn’t appear to be consensus](http://wiki.openstreetmap.org/wiki/WikiProject_Oil_and_Gas_Infrastructure#Tags_currently_in_use_for_Oil_and_Gas_Infrastructure) around a particular tagging scheme for oil fields yet. The only common tag is specifically for [offshore fields](http://wiki.openstreetmap.org/wiki/Tag:waterway%3Doffshore_field). So I only added a preset for individual wells, to be applied to points.

Added oil well preset

---

data/presets/presets.json
data/presets/presets/man_made/petroleum_well.json
data/taginfo.json

@gregcrago pointed out that the oil well preset added for #2618 actually adds `man_made=mast` instead of `man_made=petroleum_well`, due to my copy-pasta. :disappointed:

Corrected oil well preset tag

---

js/id/ui/preset/wikipedia.js

If you paste a full Wikipedia URL into the Wikipedia preset field, iD tries to detect the Wikipedia language edition and normalize the tag value to the `xy:Foo` format. It also round-trips from this format back to a URL for the link button. This PR fixes a few edge cases around these normalization steps:
- Some Wikipedia subdomains contain hyphens, e.g. zh-min-nan.wikipedia.org.
- Some Wikipedia subdomains have variants, so paths such as zh.wikipedia.org/zh-hk/ are possible.
- When a map feature is covered by a section of a Wikipedia article, but not a full-blown article, the tag value can contain an anchor. MediaWiki has a special format for anchors that looks like URL encoding ([example](https://zh.wikipedia.org/zh-hk/%E8%8C%AB%E6%9B%B2%E9%95%87#.E8.A1.8C.E6.94.BF.E5.8C.BA.E5.88.92)), …

Tighten up Wikipedia URL handling

---

data/address-formats.json

Ireland got postcodes (aka 'eircode') today. This (untested) patch adds the "postcode" field to Irish address format using the method recommended.
See the example here: http://www.irishtimes.com/news/ireland/irish-news/eircode-q-a-things-you-need-to-know-about-the-new-system-1.2283200

Add Irish postcode field

---

js/id/core/connection.js
test/spec/core/connection.js

Relevant to https://github.com/strava/iD/issues/5#issuecomment-109800372

Use HTTPS if location protocol is HTTPS in iD.Connection

---

js/id/presets/preset.js

"terms" lists that are not fully lowercase or used combinations of whitespace and commas as separators (instead of just commas) could not be handled properly. This PR fixes that.
Improved version of #2767 after feedback there.

Fix "terms" translations (closes #2756)

---

js/id/services/taginfo.js
js/id/ui/raw_tag_editor.js
js/id/ui/tag_reference.js
test/spec/taginfo.js

instead of just key.
* Pass the value to iD.ui.TagReference in the `context` function of iD.ui.RawTagEditor
* Let iD.taginfo query the docs for the key when its callback returns false.
* Let the callback function defined inside iD.ui.TagReference return false when both of these are met:
* it isn't happy with the docs results AND
* it was called with its softfail argument set to true.
Closes #2754.

Make raw tag editor show docs for key=value

---

js/id/presets/collection.js
js/id/presets/preset.js

Terminates #2756 and PR #2772 - trimming terms before using them is needed for some translations where whitespaces are inserted at string start/end. Note that function `leading` tend to handle that but not for everything actually (only spaces).

preset.js: trim terms when retrieving translations to avoid white spaces

---

js/id/ui/raw_tag_editor.js

Implements special casing of relation type tags as described in https://github.com/openstreetmap/iD/issues/2797#issuecomment-145907014. Fixes #2797

Fetch proper tag-references for relation types in raw tag editor

---

js/lib/index.html

Seems to have been added by accident from the pull request #2106.
It was part of this commit https://github.com/openstreetmap/iD/commit/dcaea5594c434d2d6ea51dc6ca7f121106115dfd and it doesn't appear to be related.

Remove Strange HTML file from lib folder

---

js/id/id.js

Use navigator.languages preferences when available. This allows a preferred language to be set in Chrome without needing to change the primary language of the OS.  This appears to only apply when iD is running outside of openstreetmap.org, as we are doing for the loggingroads.org project. When it is framed inside osm, the osm user profile language settings appear to override the browser settings.
also see: https://alicoding.com/detect-browser-language-preference-in-firefox-and-chrome-using-javascript/ and http://www.w3.org/html/wg/drafts/html/master/webappapis.html#dom-navigator-languages

better support for browser language preferences

---

data/core.yaml
dist/locales/en.json
index.html
js/id/actions/join.js
js/id/actions/reverse.js
js/id/core/entity.js
js/id/core/tags.js
js/id/geo/multipolygon.js
test/index.html
test/spec/actions/join.js
test/spec/actions/reverse.js
test/spec/geo/multipolygon.js

Fixes #2358.
"Uninteresting" tags are exempted -- this includes "attribution", "created_by", "source", "odbl", and "tiger:*". The values of such tags will continue to be joined with semicolons.
The rule also takes into account tag values that will automatically be reversed when the ways are joined. For example, if you have a `oneway: yes` way from a to b, and a `oneway: -1` way from c to b, joining is permitted, and will produce a `oneway: yes` way going a to b to c.

Disable joining ways with conflicting tags

---

test/spec/core/way.js

Whilst going through the tests I noticed that the core/way.js test for #copy is using Entity() for some reason rather than Way(). I'm pretty sure this should be Way().

Correct iD.Way test to use Way() not Entity()

---

js/id/id.js

Fix iD.detect when navigator.languages is empty.

Fix iD.detect when navigator.languages is empty.

---

data/imagery.json
data/update_imagery.js
js/id/renderer/background.js
js/id/renderer/background_source.js
js/id/ui/background.js

* Sorts the `best` imagery at the top of the background list
* Pick it automatically if the url hash doesn't specify an imagery source
* Also bump "none" to the bottom of the list
* re: #2826 #1310
cc @pnorman @planemad @lxbarth thoughts?
Before|After
--- | ---
#map=14.96/8.2276/47.5272 | #map=14.96/8.2276/47.5272

Prefer imagery marked as `best` in editor-imagery-index

---

js/id/renderer/map.js
js/id/renderer/tile_layer.js
js/id/svg.js
js/id/ui/map_in_map.js

See #2849 for details.
I've tested this on OS X with latest Chrome, Firefox, and Safari.  It seems to make iD much less jumpy and performs just as well as before, or possibly a little faster.
Could use a few more :eyes: for testing...

Eliminate rounding causing jumpiness and loss of precision

---

js/id/core/connection.js
js/id/ui/commit.js
test/spec/core/connection.js

Autocomplete changeset comments from previous changeset comments

---

js/id/ui/preset/localized.js

Shows the default user language for translated names.
in ref to issue: https://github.com/openstreetmap/iD/issues/2882

Use user language for default translated names

---

js/id/modes/add_line.js

make sure DrawLine mode is called with a clean pre-operation graph

---

js/id/renderer/background_source.js
js/id/renderer/mapillary_layer.js
js/id/ui.js
js/id/ui/feature_list.js
js/id/ui/preset/wikipedia.js
js/id/ui/tag_reference.js
test/spec/ui/preset/wikipedia.js

change of all http:// URIs in js/id folder to //.
(closes #2960)

HTTPS sensitive URIs

---

FAQ.md

Fix a typo

---

data/presets/presets/highway/track.json

**Purpose:** to clarify that `highway=track` is not a trail / single-**track** trail.
I've noticed that particularly in the MTB community there's a trend of classifying trails as `highway=track` because "Track" is a common word to refer to single-track trails (e.g. [changeset/29897324](https://www.openstreetmap.org/changeset/29897324#map=16/37.6216/-119.0007))
Most of the road presets have a "Road" suffix that make it clear you're adding a road, but the track preset does not. In its current form it's too abstract, I feel. This PR aims to make it a little more clear what you're adding.
Relevant: [BLM Road Classifications](http://www.blm.gov/id/st/en/prog/planning/Travel_Management/Craters_of_the_Moon/Road_Trail_Classifications.print.html) (Class D)

[Preset] Clarification: "Track" → "Two-Track Road (Primitive)"

---

data/presets/README.md

After running make, the presets are actually in `dist/presets.js`.

README: correct wrong path

---

FAQ.md

It took me a while to find it out. I guessed it would be in a separete config file, but it wasnt.
btw, I really wonder, how is the API url set up in the embeded iD in ruby-port. It uses correctly the my own server. Do you know how? :)

FAQ.md: api url config in standalone iD

---

data/core.yaml
dist/locales/en.json
js/id/ui/commit.js

Fixes #3063
This moves a check that's very common in our post-changeset validation up before the user even makes the mistake. This _doesn't_ prevent the user from saving the changeset yet. We may want to do that in a second pass, but there are innocuous ways to mention Google, like "This feature isn't in Google Maps, but it does exist.", so blocking save entirely is probably _too_ strong.
cc @geohacker @bhousel for the review

add a warning to the changeset page if a user mentions google

---

js/id/ui/raw_member_editor.js

There is a nasty bug when using the Raw Member Editor to set the "role" of a relation member.  The `member` argument to `iD.actions.ChangeMember` was constructed wrong, causing the relation to become corrupted. 
I'm not 100% sure that this caused https://github.com/openstreetmap/iD/issues/2739#issuecomment-210112137 but it seems possible.
:eyes: @jfirebaugh

Fix member argument to ChangeMember when using raw member editor

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/amenity/prison.json
data/taginfo.json
dist/locales/en.json

Add prison preset

---

js/id/ui/preset/localized.js

This was partly implemented on the placenames feature (adding a placename in "Chinese" shows you a list of localized options such as 中文)
The issue is that the box closes if it falls below d3.combobox minItems threshold . So if you start typing "ta" for Tamil, you will see many results whose English names contain "ta" (Tibetan at the top, Tamil close to the bottom if you scroll down). When you type "tam", there is only one matching option, so the combobox hides and your string cannot be completed.
This PR sets the minItems to zero, so you will see தமிழ் left over. If there are no results, the box will disappear.  Fix for #3023

Look up languages by English or local names [closes #3023]

---

css/app.css
js/id/ui/background.js

It's sometime convenient to quickly switch between two backgrounds, this PR adds a 'S' shorcut for this purpose.

Add 'I' shortcut for switching between the last two backgrounds.

---

Makefile
index.html
js/id/id.js
js/lib/id/presets.js
modules/presets/category.js
modules/presets/collection.js
modules/presets/field.js
modules/presets/index.js
modules/presets/preset.js
modules/presets/presets.js
test/index.html
test/rendering.html
test/spec/presets.js

The only change I had to make to namespaces was that `iD.presets` itself used to be a function; I moved it to `iD.presets.presets`.

migrate presets to ES6 modules for #3118

---

modules/.eslintrc
package.json

Currently linter doesn't support static analysis of modules( like checking if they actually exist or not).
This PR adds [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) to dev dependency and will allow us to throw error if a module is malformed / undefined.

Allow linter to do static analysis on modules

---

data/presets/categories/path.json

I think it's important to have this preset in the Path Category. More information about this tag: 
* https://www.mapbox.com/blog/mapping-sidewalks/
* https://wiki.openstreetmap.org/wiki/Sidewalks

Add sidewalk preset to Path presets category

---

css/app.css

This should fix #3100, where the background colour of form inputs had been set to white, and firefox was then using the dark theme’s light text colour which had poor contrast.
A solution is to also define a sane `color` property.

When setting a form’s background colour, also set the text colour

---

modules/presets/collection.js
modules/presets/preset.js
modules/util/util.js
package.json
test/spec/presets/collection.js

tldr: it means that strings like "fussball" will fuzzy match strings like "fußball"
more details:
In `collection.js` search results are returned in the following order:
1. match name
1. match terms
1. match tag value
1. similar name
1. similar terms
Diacritical marks are only replaced when calculating the "similar" search results string distance, so this is a fallback strategy from strict string matches.
(closes #3159)
I also 
cc @1ec5

Replace diacritics when doing fuzzy searches

---

modules/core/history.js
modules/geo/multipolygon.js

These are the two remaining cases of relying on iD _funcitonality_ via the global iD variable. The remainder are cases where we rely on iD.data or something similar, like iD.areaTags.

Inter-require iD instead of relying on the global

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/second_hand.json
data/presets/presets.json
data/presets/presets/shop/car.json
dist/locales/en.json

Hi, 
I added the second_hand= tag to the preset. The tag is used to denote for shops whether the merchandise is used. It's used over [4,000 times ](http://taginfo.openstreetmap.org/keys/second_hand#values) so far in the planet. 
One common use of the second_hand tag is to designate a used car lot. I've also added the second_hand tag in this pull request.

add second_hand tag in preset and second_hand field for shop=car

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/emergency/defibrillator.json
dist/locales/en.json

AED, short for Automated External Defibrillator, is a term known by many people and often marked on defibrillators. Was also originally requested in #3202:
> Would be ideal if this came up when either "defibrillator" or "AED" was searched for.

Add AED as term for Defibrillator

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/indoor.json
data/presets/presets.json
data/presets/presets/emergency/defibrillator.json
dist/locales/en.json

Doing this separately from #3283 because this adds a new field and I'm not sure you're OK with it.
I add `indoor=yes` to all AEDs I map that are located inside a building.

Add indoor=yes/no to preset for Defibrillator

---

modules/services/taginfo.js

When suggesting values for `network` or `cycle_network` from taginfo, include values that contain uppercase letters. This effectively enables taginfo suggestions for the`cycle_network` tag where previously they were completely disabled, and suggestions for the `network` tag are more accurate as well.
Presumably the uppercase filter was originally intended to block suggestions for freeform tags like `name`. But `network` and `cycle_network` aren’t entirely open-ended, even though their values contain uppercase letters.
/cc @bhousel

Allow uppercase in network taginfo

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/cycle_network.json
data/presets/fields/network_bicycle.json
data/presets/fields/network_foot.json
data/presets/presets.json
data/presets/presets/type/route/bicycle.json
data/presets/presets/type/route/foot.json
data/presets/presets/type/route/hiking.json
dist/locales/en.json
modules/services/taginfo.js

Replaced the generic Network field (`network`) with a specialized Network Type field (`network`) in the bicycle, foot, and hiking route relation presets. Added a Network (`cycle_network`) field to the cycling route relation preset.
_Cycling route relation fields_
_Cycling route network types_
The combo values for the cycling route relation preset conform to [wiki guidelines](http://wiki.openstreetmap.org/wiki/Tag:route%3Dbicycle) and common usage:
* Local (`network=lcn`)
* Regional (`network=rcn`)
* National (`network=ncn`)
* International (`network=icn`)
The combo values for the walking and hiking route relation presets also conform to [wiki guidelines](http://wiki.openstreetmap.org/wiki/Tag:route%3Dhiking):
* Local (`network=lwn`)
* Regional (`network=rwn`)
* National (`network=nwn`)
* …

Combo Network Type field for bike/hike routes

---

modules/ui/fields/combo.js

Each combo value obtained from taginfo now has a tooltip describing the value, if available.
(taginfo suggestions in the “All tags” section already have descriptive tooltips.)

taginfo tooltips for combo values

---

modules/presets/preset.js
modules/services/taginfo.js

taginfo’s relation/wiki_pages method no longer places results in a `data` property.
Also, only use relation/wiki_pages for top-level relation presets. More specific presets behave like non-relation presets. For example, the bicycle route relation has the tags `type=route` `route=bicycle`, so `route=bicycle` is what we’re interested in.
Fixes #3297.
/cc @bhousel

Fix taginfo for relation presets

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/cycle_network.json
data/presets/fields/network_road.json
data/presets/presets.json
data/presets/presets/type/route/road.json
dist/locales/en.json
modules/ui/fields/combo.js
modules/ui/fields/index.js

Added a variation of the combo field for road networks. If the field’s value is blank or shares a prefix with the current country code, search taginfo for values beginning with the country code and a colon.
`network` values for road routes generally begin with the country code (either uppercase or lowercase) followed by a colon. The one big exception is Ontario: 2,023 are relations tagged [`network=ca_on_county`](http://taginfo.openstreetmap.org/tags/network=ca_on_county), so overall there are 1,500 elements tagged `network=CA:*` versus 2,429 tagged `network=ca_*`. On the other hand, 2,478 bus stops are tagged [`network=co:dc:sitp`](http://overpass-turbo.eu/s/hBi), which does begin with the country code and a colon. Also, a few popular values in Europe are unqualified letters. Despite …

Combo field with taginfo for road networks

---

modules/services/taginfo.js
modules/ui/raw_member_editor.js
modules/ui/raw_membership_editor.js
test/spec/services/taginfo.js

Enabled taginfo suggestions for roles on relation members and memberships.

taginfo for relation roles

---

modules/util/util.js

If a relation is tagged with a `network`, the `network` is needed alongside the `ref` to identify the relation.
For example, this Ohio State Route relation is tagged `type=route` `route=road` `network=US:OH` `ref=28`, while its members are tagged `ref=SR 28`:
Displaying the network will make mappers less inclined to redundantly tag the network-ref combination in `name`.

Include network in relation display name

---

build.js

Preset validation failed to identify schema errors because `jsonschema.validate(instance, schema).length` is always `undefined`.
This PR checks `jsonschema.validate(instance, schema).errors` instead.

Fixed validate function

---

README.md
package.json

http-server for node.js is very convenient, and is a lot faster than Python's SimpleHTTPServer. This is primarily because it uses asynchronous IO for concurrent handling of requests, instead of serialising requests.
> 🎶  it's a node world after all 🎶 
Enjoy the ride! https://www.youtube.com/watch?v=iJFGAX77zw4

Change instructions to use node's http-server instead of going into python land

---

data/presets/presets/place/locality.json

As per the wiki, place=locality is for unpopulated places

Remove population from locality

---

README.md

Presumably either the Command Line Tools package or Xcode would install the tools needed for the build system.
/cc @bhousel

Simplify macOS setup instructions

---

data/presets/presets/emergency/fire_hydrant.json

Fire hydrants are for firemen anyway, and it help distinguish them from other no-icon point on the map. 
By the way, is there any plan to upgrade maki from version 0.5.0 to latest version 2.0.x? Is that OK if I migrate iD by updating icons' name or there is a particular reason to use maki 0.5.0?

Add fire-station icon for fire-hydrant

---

data/presets/fields/date.json
data/presets/fields/display.json
data/presets/fields/support.json
data/presets/fields/visibility.json
data/presets/presets/amenity/clock.json

For later better [rendering of clocks](https://github.com/gravitystorm/openstreetmap-carto/pull/2218) i added the tags "support", "display", "visibility", "date" to clock presets.

Added more fields to clock preset

---

modules/core/way.js

parseInt should always have a radix.
Even if i have not found a problematic value (leading zero) in Taginfo. Surprising :-)
Removed one call of parseInt which was called on a number.

parseInt cleanup

---

modules/core/way.js

Hello.
Now layer() returns only a finite number, not NaN.
/* Chrome 53 */

Fix way disappearing due to invalid "layer" tag

---

data/presets/presets/shop/e-cigarette.json

https://wiki.openstreetmap.org/wiki/Tag:shop%3De-cigarette
Only 500+ uses but more popular than some of the preset tags in iD, and helps with consistent tagging.

Add e-cigarette shop preset

---

css/app.css
modules/ui/background.js
modules/ui/entity_editor.js
modules/ui/geolocate.js
modules/ui/help.js
modules/ui/init.js
modules/ui/map_data.js
modules/ui/preset.js
modules/ui/preset_list.js
modules/ui/undo_redo.js
modules/ui/zoom.js
modules/util/detect.js
modules/util/locale.js
modules/util/util.js

Addresses #3007 - right-to-left languages (Arabic and Persian are available in iD editor)
Here's what it looks like (using English locale and ```?rtl-test-rtl``` in the URL)
I might be missing some tooltips... if someone is an Arabic or Persian speaker and can check this out with the language locale on, that'd be great

Add right-to-left language layout to CSS

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/shop/beauty/nails.json
data/taginfo.json
dist/locales/en.json

Here's a pull request that adds nail salons (where people have their fingernails lacquered and/or manicured) to the generic preset. 
The common tags for tagging these are shop=beauty and beauty=nails. [taginfo](http://taginfo.openstreetmap.org/search?q=nails#values) and [wiki](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbeauty)
I wasn't sure on the correct file location for this preset but I created a new folder within the shop folder, and 
named it after its parent tag, beauty. 
This structure is based the practice of presets whose meaning are not defined so much by their first tag but rather by their second tag. This occurs with a mosque which has amenity=place_of_worship and religion=muslim)[https://github.com/openstreetmap/iD/tree/master/data/presets/presets/amenity/place_of_worship …

add preset for nail salon

---

index.html
modules/services/osm.js
package.json

This attempts to make authenticated calls to the OSM API if the user is logged in.
(see https://github.com/openstreetmap/iD/issues/2262#issuecomment-253215027)
I'm still having some trouble with the map call.  The server is not too happy with my attempt to send OAuth headers.  Any ideas @zerebubuth ?
Full headers for a typical map call look like this:
```
Request URL:http://www.openstreetmap.org/api/0.6/map?bbox=-74.53674316406232,40.66397287638667,-74.53124999999982,40.66813955408022
Request Method:GET
Status Code:401 Internal Server Error
Remote Address:193.63.75.103:80
```
```
HTTP/1.1 401 Internal Server Error
Date: Mon, 24 Oct 2016 05:20:02 GMT
Server: Apache/2.4.18 (Ubuntu)
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: …
```

Authenticate OSM API calls

---

build.js

Adds an additional presets consistency check at build time to ensure `defaults.json` refers to categories and presets that actually exist.

Validate preset defaults at build step

---

css/map.css

A change that turns everything red - well actually only farmyards - and those orange.
Right now, farmyards are not defined in iD CSS, which result in them being colored forest-green while editing. Green is not an intuitive color for a human-centric area. And farmyards are fairly common when mapping, so it seems important that they should have a distinct color.
I used a modified copy of the CSS code for residential areas, and changed the color to the same orange used for farmyards on the standard openstreetmap layer on osm.org.

Custom color for farmyards.

---

css/map.css
modules/lib/d3.keybinding.js
modules/modes/select.js
modules/ui/init.js
modules/ui/zoom.js
test/spec/lib/d3.keybinding.js

Today I played around with keyboard navigation for vertexes.  
This closes #1917 and adds some useful keyboard shortcuts:
`[` - jump to previous vertex
`]` - jump to next vertex
`⌘[` - jump to first vertex
`⌘]` - jump to last vertex
Also it: 
* handles circular ways (can jump next/previous across the connecting node)
* adds interpolated viewport following  (see #3250 - which is this but in the draw modes)
* when navigating across a vertex with multiple parents, remembers which line to stay on
There are still a few weird things to clean up - e.g. it's possible for the vertex to go unselected when jumping to one that's offscreen.
Also I'd like to try to support a shift modifier, which woud let you add or remove nodes from the selection.

Add vertex keyboard navigation

---

modules/lib/d3.keybinding.js
modules/ui/zoom.js

The underscore key is referenced in [zoom.js](https://github.com/openstreetmap/iD/blob/master/modules/ui/zoom.js#L78), but not defined as a keycode. This resulted in a keycode=0 definition [here](https://github.com/openstreetmap/iD/blob/master/modules/lib/d3.keybinding.js#L67-L87), which is potentially triggered by special keyboard keys (for example, on my keyboard the [Fn](https://en.wikipedia.org/wiki/Fn_key) key produces such an event).

add missing keycode for underscore

---

data/core.yaml

{zoom} is the default and should be used. See also osmlab/editor-layer-index/issues/226

update docu - use {zoom} instead of {z} for TMS URLs

---

RELEASING.md

Escape '\*' characters for correct display in Markdown.
Do not add force dist/locales/\*.json files, that are not ignored in master branch.

improve release algorithm

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/amenity/crematorium.json
data/presets/presets/amenity/food_court.json
data/taginfo.json
dist/locales/en.json

http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcrematorium
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfood_court

add presets to amenity=food_court and amenity=crematorium

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/camera/direction.json
data/presets/fields/camera/mount.json
data/presets/fields/camera/type.json
data/presets/fields/contact/webcam.json
data/presets/fields/surveillance.json
data/presets/fields/surveillance/type.json
data/presets/fields/surveillance/zone.json
data/presets/presets.json
data/presets/presets/man_made/surveillance.json
dist/locales/en.json

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance
https://wiki.openstreetmap.org/wiki/Proposed_features/Extended_tags_for_Key:Surveillance
These are mandatory tags:
* `surveillance`
* `surveillance:type`
I do not feel that the following are important, they can be selected from
the drop down manually anyway:
* `operator`
* `name`
These tags are well established:
* `camera:type` has 15k users
* `camera:mount` has 13k users
* `surveillance:zone` has 17k users (mostly traffic is noted)
* `camera:direction` has 6k users
These tags are in the proposed status:
* `contact:webcam` usage is only starting
* `height`
People used various tags instead of `contact:webcam` in the past
because of it being a recent tag, and/or a lack of knowledge or being
mislead by the dropdown.
Thus it is …

data/presets: add surveillance and camera related properties

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/bath/open_air.json
data/presets/fields/bath/sand_bath.json
data/presets/fields/bath/type.json
data/presets/presets.json
data/presets/presets/amenity/public_bath.json
data/taginfo.json
dist/locales/en.json

A simple public bath scheme, as specified [on OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_bath).

Public bath scheme

---

data/core.yaml
dist/locales/en.json

Fix errors in console after reflect-operation on single object.
> Missing en translation: operations.reflect.annotation.short.single
> Missing en translation: operations.reflect.annotation.long.single

Fix reflect-typo

---

modules/behavior/select.js
modules/modes/select.js

For discussion https://github.com/openstreetmap/iD/issues/3682.
Double-click to a midpoint makes a vertex instead of zooming.

Make vertex by midpoint double-clicking

---

modules/util/svg_paths_arabic_fix.js

Along with the recent changes in #3707, found a bug with various cases when the string contains a space. So wrote a quick fix for it.

fix a bug with space

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/amenity/_coworking_space.json
data/taginfo.json
dist/locales/en.json

In 23a37183762adb2b1fe044b9bee3b50d5095eff3 `amenity=coworking_space` was changed into `office=coworking`.
I'd propose to add a **non-searchable preset** for `amenity=coworking_space` so it doesn't show up as a blank Amenity in the Inspector.

Add amenity=coworking_space as non-searchable preset

---

data/address-formats.json

This PR adds Turkish address scheme defined [here](http://postakodu.ptt.gov.tr/Dosyalar/adres.pdf). That is an official documentation, but only available in Turkish.
The scheme is defined as (in Turkish):
* Mahalle / Köy
* Bulvar/ Cadde / Sokak / Mevki / Site / Blok / Bina ismi / Dış Kapı No / Kat / İç Kapı No
* Posta kodu / Bucak (Semt) / İlçe / İl / Ülke 
That maps to English as:
* Neighborhood
* Street, House number
* Postal code, District, City

Add Turkish address scheme

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/outdoor_seating.json

This PR adds `outdoor_seating` options following [OSM wiki](http://wiki.openstreetmap.org/wiki/Key:outdoor_seating).

Add outdoor_seating options

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/aerialway/drag_lift.json
data/presets/presets/aerialway/goods.json
data/presets/presets/aerialway/mixed_lift.json
data/taginfo.json
dist/locales/en.json

Adds additional aerialway presets, fixes #3733

---

modules/ui/index.js

````
export * from './ui/fields/index';
export * from './ui/intro/index';
export * from './ui/index';
````
uiFields and uiIntro are redefined through `export * from ..`. I remove them them from `./ui/index`, because nobody call them from `./ui/index`

fix: properties exported are redefined

---

modules/ui/commit.js

This makes sure no duplicate commit messages are suggested.
The issue illustrated:
I had to add a container variable to be able to use `indexOf`, the alternative would have been a loop as far as I know...

Do not suggest duplicate commit messages

---

modules/core/context.js

While it makes sense to not save the state of the history in save mode (see 15bc08795d5a0daaeaddd804cdc6729e1dfff848) we should still display the *"You have unsaved changes"* browser message. This should remind people that changes are not actually saved unless the second save button is also pressed (see #3777).

show "You have unsaved changes" message also in save mode

---

data/core.yaml
dist/locales/en.json
modules/svg/gpx.js

After @bhousel's comment on https://github.com/openstreetmap/iD/pull/3808 I updated existing gpx layer, added ability to read in .kml and .geojson files based on file extension.

Add kml and geojson support to gpx layer

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/office/lawyer/notary.json
data/taginfo.json
dist/locales/en.json

Adding a commonly used tag for a notary office. It has more than a thousand uses on the map.
https://wiki.openstreetmap.org/wiki/Tag:office%3Dlawyer
http://taginfo.osm.org/tags/lawyer=notary

Add notary preset

---

modules/svg/gpx.js

The original implementation only worked for Points and LineStrings, but GeoJSON and KML can contain any geometry.
Aso, d3 is a bit [special](https://github.com/d3/d3-geo#d3-geo) when working with GeoJSON Polygons: it does require clockwise winding, but typical GeoJSON uses either counterclockwise winding ([RFC7946](https://tools.ietf.org/html/rfc7946#section-3.1.6)) or "winding doesn't matter" mode (old geojson.org spec). When inputing such GeoJSON (or KML) input, iD would zoom out all the way, which is not the intended behavior.

improve autozooming on non-gpx background data layers

---

development_server.js

I noticed rollup provides [cache](https://github.com/rollup/rollup/wiki/JavaScript-API) to speed up subsequent builds.
I am noticing 30-40% improvement.  😎 ( from 8500ms to 5000ms)

Use cache to speed up development

---

modules/services/osm.js
test/spec/services/osm.js

This patch fixes #3208. In details:
* New relations are ordered in the changeset so that children appear in the file before their parents.
* Circular dependencies are not ordered because it is not possible. In this case, an osmChange will be generated, but the API will return an error. Ideally, the user interface should prevent users from creating circular dependencies. Hence, this case should not happen.
* The bug is specific to creations. I do not think that  we need a similar fix also for modifications and deletions.
Hope everything ok. Otherwise please let me know! :)

Order to-be-created relations by dependencies in the changeset

---

package.json

`npm install` was failing on Windows due to the single quotes added to `dist:min` in https://github.com/openstreetmap/iD/commit/bb9b4b87251dd4f28f358dc6ef543e4f43e11b73. Removing the single quotes makes it work install again successfully, and does not cause problems on OSX builds either.

Update package.json to fix dist:min script on Windows

---

css/80_app.css
modules/modes/save.js
modules/osm/changeset.js
modules/services/osm.js
modules/ui/commit.js
modules/ui/raw_tag_editor.js
modules/ui/success.js
test/spec/osm/changeset.js
test/spec/services/osm.js

This will let users add and edit changeset tags before saving. 
re: #2834, #2633 
* The raw tag editor will always start out closed in this case. 
* No taginfo support for changeset tags, so dropdowns and tag autocompletion are disabled
* TODO:  The default iD tags will be protected and not allow editing.

Embed a raw tag editor on the commit pane

---

css/80_app.css
data/core.yaml
data/presets/README.md
data/presets/fields.json
data/presets/fields/structure.json
data/presets/schema/field.json
dist/locales/en.json
modules/ui/fields/index.js
modules/ui/fields/radio.js
modules/ui/raw_tag_editor.js

(for #2087)
There are still a few cleanups to do before merging, and I want to make the `type` field a combo.

Add type and layer subfields below structure radiobutton field

---

css/50_misc.css
modules/behavior/hash.js
modules/modes/select.js
modules/renderer/map.js
modules/svg/lines.js
test/spec/svg/lines.js

This is a fix for #2914 to draw any selected ways in a separate group after the unselected ways.
Code still needs some cleanup

Draw selected objects after not-selected objects

---

modules/util/svg_paths_rtl_fix.js
modules/util/util.js

This takes the Arabic-specific regex and fix which we implemented earlier, and extends it to two other right-to-left scripts (Hebrew, and Thaana from the Maldives)
These two languages don't need special text-shaping like we did for Arabic, just right-to-left reversal to handle the Chrome bug, and keeping vowel signs together with the letter that they modify (sort of like ```N + ̃  = Ñ``` - reversing the string should not change which letter gets the tilde)
The Arabic code also gets the fix for vowel signs

Support Arabic vowel signs, include more languages in generic RTL fix

---

README.md

I updated http links in the readme that would otherwise automatically be redirected to https by the website, to just use https directly. :)
Thank you again for making an awesome editor! ^ _ ^
I'd like to note that links in this section of the readme
"
Test a prerelease version of iD:
Stable mirror of release branch: http://openstreetmap.us/iD/release
Development mirror of master branch: http://openstreetmap.us/iD/master
"
Currently 404. I'm not sure if this is temporary or permanent.

Updated http links to https

---

CONTRIBUTING.md
data/core.yaml
dist/locales/en.json

Hopefully this is the corrected version of https://github.com/openstreetmap/iD/pull/3958
I also updated the CONTRIBUTING.md to explain how to make these updates to `core.yml` in the future, as I think it was missing that info.
I'm not sure why it moved `place/city` beneath `place/farm` but I think it was part of the npm build script?

Updated Merge Messaging + CONTRIBUTING.md

---

modules/services/nominatim.js
modules/services/taginfo.js
test/spec/services/taginfo.js

for #3955 
There is a lot going on here, so I'm rolling several changes into a PR.  The goal here is to significantly reduce the number of taginfo lookups that iD is doing, as most of them are unnecessary and they're starting to degrade the server performance.
cc @Joto

Taginfo improvements

---

data/address-formats.json

As Ukrainian OSM Community don't fill in `addr:city` for each building, It is better to decrease amount of fields for adding addresses.
>Теґ addr:city=* в Україні зазвичай не використовується.
☝️ https://wiki.openstreetmap.org/wiki/Uk:Addresses

Added fields for address in Ukraine

---

data/presets/presets.json
data/presets/presets/highway/cycleway.json
data/presets/presets/highway/living_street.json
data/presets/presets/highway/motorway.json
data/presets/presets/highway/motorway_link.json
data/presets/presets/highway/primary.json
data/presets/presets/highway/primary_link.json
data/presets/presets/highway/raceway.json
data/presets/presets/highway/residential.json
data/presets/presets/highway/road.json
data/presets/presets/highway/secondary.json
data/presets/presets/highway/secondary_link.json
data/presets/presets/highway/service.json
data/presets/presets/highway/tertiary.json
data/presets/presets/highway/tertiary_link.json
data/presets/presets/highway/trunk.json
data/presets/presets/highway/trunk_link.json
data/presets/presets/highway/unclassified.json

The `structure` and `access` fields takes too much space in the screen and are less used than `surface` and `lanes`, so I change the ordering to show more fields on the screen without the need of scrolling. 
**Before:**
**After:**

Change ordering in highway fields presets

---

modules/ui/feature_list.js

After `delete iD.services.geocoder`.

Omit global search UI when no geocoder service is available

---

css/80_app.css
data/core.yaml
data/shortcuts.json
dist/locales/en.json
modules/ui/cmd.js
modules/ui/shortcuts.js

Some improvements for the items in #4073 
* replace "left-click"/"right-click" with mouse icons to save space
* split modifiers from key array
* add separator for key array (can be char like `,` or a string like "-or-")
* change display of certain keys for Mac/Windows (see below):
```js
var detected = utilDetect();
var mac = (detected.os === 'mac');
var replacements = {
'⌘': mac ? '⌘ Cmd'       : 'Ctrl',
'⇧': mac ? '⇧ Shift'     : 'Shift',
'⌥': mac ? '⌥ Option'    : 'Alt',
'⌫': mac ? '⌫ Delete'    : 'Backspace',
'⌦': mac ? '⌦ Del'       : 'Del',
'↖': mac ? '↖ PgUp'      : 'PgUp',
'↘': mac ? '↘ PgDn'      : 'PgDn',
'⇞': mac ? '⇞ Home'      : 'Home',
'⇟': mac ? '⇟ End'       : 'End',
'↵': mac ? '↵ Return'    : 'Enter',
'⎋': mac ? '⎋ Esc'       : 'Esc',
};
```

Keyboard shortcuts pt2

---

modules/lib/d3.keybinding.js
modules/ui/map_in_map.js

This is a try on improving compatibility across different keyboard layouts (e.g. used by different language groups): Use the new [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) API (if available, but most browsers already have it, only Safari seems to be a bit behind on this – for which old-style keyCodes are used as a fallback).
I've tested it on Firefox (Linux) and Chrome and IE11 (both on Windows) and there it seems to work very well. But there's a strange bug in Chrome on Linux (see this ~~[ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=663339)~~ [ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=633838) (which will apparently be fixed in Chrome v56+) which renders the important undo/redo and zoom shortcuts `Ctrl + …

implement keyboard shortcuts using KeyboardEvent.key api

---

css/80_app.css

After uploading changes, the "view on osm.org" link is currently unclickable (until one reloads the whole page). This is because the order of the divs in the `.inspector_wrap` gets inverted for some reason (I don't see why, though[?](https://github.com/openstreetmap/iD/blob/master/modules/ui/inspector.js)). Adding this z-index helps keeping it on top of the rest of the inspector pane and the link clickable.

make sure inspector footer stays on top

---

CONTRIBUTING.md

greetings!
just proposing a small tweak in the `CONTRIBUTING` regarding supplementing iD's documentation
* removed section about alphabetical order of help, as it doesn't seem to be relevant anymore
* added a breadcrumb to let folks know what is required to see changes after adding new doc:
* add a new `docKey` in /modules/ui/help.js
* run `npm run build`/`node build.js` to write to /dist/locales/en.json

clarify extra steps necessary to add new app documentation

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/milestone_position.json
data/presets/presets.json
data/presets/presets/railway/derail.json
data/presets/presets/railway/milestone.json
data/presets/presets/railway/signal.json
data/presets/presets/railway/switch.json
data/presets/presets/railway/train_wash.json
data/presets/presets/railway/wash.json
data/taginfo.json
dist/locales/en.json

This is to, fix #4193 
So far I have added
- Railway Derailer
- Railway Milestone
- Railway Signal
- Railway Switch
- ~~Railway Wash~~ Train wash (6da0719f3a49d4173fe4769e2522a2edccd62885)
Todo:
This could also change the car_wash icon, as currently it is just a car, and looks like a few other presets, this is also the same for railways. So I thought we could maybe add some brushes around the side like shown:
All we need to do is change the car to a train, then we're done.

Adding some more railway presets

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/ref_runway.json
data/presets/fields/ref_taxiway.json
data/presets/presets.json
data/presets/presets/aerialway/station.json
data/presets/presets/aerialway/t-bar.json
data/presets/presets/aeroway/runway.json
data/presets/presets/aeroway/taxiway.json
dist/locales/en.json

This PR does the following:
- Runway now has "Runway number"
- Taxiway now has "Taxiway Name"
- T-Bar lift would not appear if "tbar" was entered, this has been changed
- Aerialway station can now be drawn as an area and as a building

Add custom references for runway and taxiway, improve searchability

---

data/presets/presets/man_made/pier.json

Looking through man_made=jetty, quite a number of them should be piers.
Think I messed up resetting github but hope this PR is ok for you (save me having to fully refork)

Add jetty term to pier

---

data/presets/presets/natural/wetland.json

I was retagging an old natural=marsh so searched for marsh in the presets, but didn't find anything. I've added the top five wetland=* values to help people find the wetland preset.
Maybe these could be made into proper presets in the future?

Add terms to wetland

---

data/address-formats.json
data/presets.yaml
data/presets/fields.json
data/presets/fields/address.json
data/presets/presets.json
dist/locales/en.json

Adding unit field to USA

---

data/address-formats.json

We have `addr:district` that works similar as `addr:unit` (in western style).
In Chinese language, the word 'unit' is translated to "单元"(a numbered entrance of a building), which is more specific than `addr:housenumber`, so there's no need to keep it.
See [https://en.wikipedia.org/wiki/Address_(geography)#China](https://en.wikipedia.org/wiki/Address_(geography)#China)
#3980 
#4235

Update Chinese address format

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/amenity/doctors.json
data/presets/presets/office/_physician.json
data/taginfo.json

and add term "physician" to `amenity=doctors`.
`office=physician` is only documented on the wiki at the seemingly abandoned Healthcare 2.0 proposal. It makes no sense to have its preset searchable. The supported tag for physicians is `amenity=doctors`.

Make office=physician non-searchable

---

data/address-formats.json

addr:unit is not common in Brazil addresses

remove addr:unit from Brazil addresses field

---

data/address-formats.json

addr:unit removed from address fields for Germany, Austria and Switzerland

remove addr:unit from address fields for Germany, Austria and Switzerland

---

data/presets/presets/shop/art.json

Combining shop=art with artwork_type seems to give nonsensical values as it is not clear that it applies to the goods sold and not to the shop, see discussion https://forum.openstreetmap.org/viewtopic.php?id=59504 and http://wiki.openstreetmap.org/wiki/Tag:shop%3Dart
Don't have a strong opinion on this myself, but for example a mural is going to be a rather difficult good to have on premises :-).

artwork_type applies to individual works of art and not to a shop

---

data/core.yaml
modules/renderer/background_source.js
modules/renderer/tile_layer.js
modules/ui/panels/background.js
modules/ui/status.js
test/spec/spec_helpers.js

resolves #4280
* restricts fetching metadata when zoomed to 13 or tighter
* adds a new line to the metadata panel when Esri imagery is active to display the individual provider (NAIP, DigitalGlobe, Municipality etc.)

add support for displaying esri metadata

---

css/80_app.css
data/core.yaml
dist/locales/en.json
modules/modes/save.js
modules/ui/commit_changes.js
modules/ui/conflicts.js
modules/util/detect.js

(WIP: still need to check IE11 and fix download on conflict screen)
closes #4346

Add download changes link

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/playground/baby.json
data/presets/fields/playground/max_age.json
data/presets/fields/playground/min_age.json
data/presets/presets.json
data/presets/presets/leisure/playground.json
data/presets/presets/playground/balance_beam.json
data/presets/presets/playground/basket_spinner.json
data/presets/presets/playground/basket_swing.json
data/presets/presets/playground/climbing_frame.json
data/presets/presets/playground/cushion.json
data/presets/presets/playground/horizontal_bar.json
data/presets/presets/playground/rocker.json
data/presets/presets/playground/roundabout.json
data/presets/presets/playground/sandpit.json
data/presets/presets/playground/seesaw.json
data/presets/presets/playground/slide.json
data/presets/presets/playground/structure.json
data/presets/presets/playground/swing.json
data/presets/presets/playground/zipwire.json
data/taginfo.json
dist/locales/en.json

Closes #4252 
- Balance Beam
- Basket Spinner
- Basket Swing
- Climbing Frame
- Bouncy Cushion
- Horizontal Bar
- Springy Rocker
- Play Roundabout
- Sandpit
- Seesaw
- Slide
- Playground Structure
- Swing
- Zipwire
- ~~Add a new field for the `swing` preset that says whether it has a special wheelchair seat~~
I changed it from `Designed for babies` to `Baby seat`, but I'm still unsure if I like this or not

Adding playground presets

---

modules/ui/preset_list.js

Fixes possible overlapping when multiple tag references are expanded.
New max-height 190 px = button 80 px + content 110 px
Closes #4023

Fixed overlapping in feature editor

---

data/presets/presets/playground/rocker.json
data/presets/presets/playground/roundabout.json
dist/locales/en.json

A couple improvements to playground presets:
* Renamed the “Springy Rocker” preset to “Spring Rider” and added “spring rocker” as a synonym. Both “[spring rider](https://en.wikipedia.org/wiki/Spring_rider)” and “spring rocker” appear to be more common than “springy rocker” in usage online.
* Added “merry-go-round” as a synonym for “Play Roundabout”.

Refine playground preset terminology

---

modules/ui/commit.js

Unicode ranges for punctuation are simpler than creating a Unicode-aware word class, so delimit on non-words.
Fixes #4398

Treat punctuation as hashtag delimiters

---

modules/ui/commit.js

@bhousel your comment in #4419 made me realize that these characters also valid: `-`, `+`, `&` (and in use)

Allow -,_,+,& as hashtag characters

---

data/presets/presets.json
data/presets/presets/place/plot.json
dist/locales/en.json

I have added a new presets JSON file for place=plot. 
I'm new to this, so let me know if I need to change anything.

Added plot preset

---

modules/behavior/copy.js

Fixes #4406
The decision allows users to copy any text nodes within the app with the copy hotkeys

Copyable content text

---

API.md
modules/renderer/features.js

Fixes #4393
`features` api parameter is added for enabling the features in the list (`,` is the splitter)
Also the hash is being updated when the user toggles features

add the features api parameter which enables the list of features

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/industrial/slaughterhouse.json
data/taginfo.json
dist/locales/en.json

Add Slaughterhouse preset

---

data/presets.yaml
data/presets/categories.json
data/presets/categories/landuse.json
data/presets/presets.json
data/presets/presets/landuse/religious.json
data/taginfo.json
dist/locales/en.json

Add landuse=religious preset

---

data/core.yaml
dist/locales/en-GB.json
dist/locales/en.json

This PR tries to decapitalise four English words in the interface of iD. In my opinion their capitalisation is not justified as they are not directly referring to a feature name of the app.
E.g. "Zoom in to edit" where edit is the standard English word. If it was referring to the Edit feature it would have to be "Zoom in to use Edit".

Do not capitalise English words.

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/office/adoption_agency.json
data/presets/presets/office/advertising_agency.json
data/presets/presets/office/association.json
data/presets/presets/office/charity.json
data/presets/presets/office/energy_supplier.json
data/presets/presets/office/forestry.json
data/presets/presets/office/foundation.json
data/presets/presets/office/government/tax.json
data/presets/presets/office/guide.json
data/presets/presets/office/moving_company.json
data/presets/presets/office/notary.json
data/presets/presets/office/private_investigator.json
data/presets/presets/office/quango.json
data/presets/presets/office/surveyor.json
data/presets/presets/office/tax_advisor.json
data/presets/presets/office/water_utility.json
data/taginfo.json
dist/locales/en.json

Adds association, advertising_agency, and surveyor office presets as requested in #4489. 
This is my first time contributing, so I'm very open to feedback!!
I also noticed there were several other presets missing that are on the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:office) (see below). Should those be added as part of a separate issue?
Here are the other ones on the OSM Wiki:
- adoption_agency
- charity
- energy_supplier
- forestry
- foundation
- guide
- logistics
- moving_company
- notary
- private_investigator
- quango
- religion
- tax
- tax_advisor
- travel_agent
- water_utility

4489 add missing office presets

---

css/60_photos.css
data/core.yaml
dist/locales/en.json
modules/renderer/background.js
modules/services/index.js
modules/services/mapillary.js
modules/services/openstreetcam.js
modules/svg/index.js
modules/svg/layers.js
modules/svg/mapillary_images.js
modules/svg/openstreetcam_images.js
modules/ui/init.js
modules/ui/map_data.js
test/index.html
test/spec/services/mapillary.js
test/spec/services/openstreetcam.js
test/spec/svg/layers.js

This PR adds support for OpenStreetCam to iD  🎉 
It works pretty ok right now, but I'll improve a few things:
cc @mvexel

OpenStreetCam Support!

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/agrarian.json
data/presets/presets.json
data/presets/presets/shop/agrarian.json
data/taginfo.json
dist/locales/en.json

https://wiki.openstreetmap.org/wiki/Tag:shop=agrarian

add shop=agrarian preset and agrarian=* field

---

data/presets/presets/shop/kiosk.json

Wiki makes no mention of it being specifically a "news" kiosk, describing it instead as selling various things. Is this country-specific usage?

Kiosk name update

---

data/presets/presets/tourism/attraction.json

If merged this will close #4563.
For example, the London Eye (classes as a tourist attraction) previously had a monument icon:
It will now have a star icon:
This pull request was made as a part of 24 Pull Requests. 
#codebar24PR2017

Changed tourist attraction icon from monument to star

---

modules/ui/curtain.js
modules/ui/intro/welcome.js

Fixes #4605
The code that controls the left click and right click portions of the welcome walkthrough removes the click counter element upon successfully clicking the required 5 times then moving onto the next chapter of the walkthrough. It does not take into account the possibility of the user clicking onto a later portion of the walkthrough while the clicking portions still have not been completed, skipping the deletion of the element altogether.
This fix adds a line to curtain.js that deletes any leftover counter elements when constructing the new tooltip.

Fixed click counter persisting

---

data/core.yaml
dist/locales/en.json
modules/ui/panels/measurement.js

As OSM has a limit of 2000 nodes in a way, some users asked me if this information could be available in iD, so I added it to the measurement panel.

add number of nodes information to measurement panel

---

css/80_app.css

Change the style of the changeset editor when the comment is empty to explicitly indicate the user what he has to do.
This PR is a minimal change to fix #4613. It only modifies the CSS for the changeset editor.
I've just seen there is another PR for this issue (https://github.com/openstreetmap/iD/pull/4621) which implements some other features that might be helpfull. I still submit mine in case a simpler fix is preferable (also, it's my first one for iD and I chose a "good first issue").
(closes #4613)

Highlight the changeset editor when the comment is empty

---

css/80_app.css
data/core.yaml
dist/locales/en.json
modules/modes/save.js
modules/renderer/map.js
modules/services/osm.js
modules/ui/commit.js
modules/ui/confirm.js
modules/ui/conflicts.js
modules/ui/intro/welcome.js
modules/ui/loading.js

This will fix a few significant bugs with saving.
- #4641 is a bug causing duplicate uploaded changesets.  This happens because, in some browsers, the save button can retain focus after it is clicked and still allow the user to press enter to activate it (even though we block clicks)
- #3056 involves a few things related to conflict resolution.  The most immediate benefit will be that iD will attempt a fast save first, then only enter the conflict resolution process if the API returns 409 Conflict.
- #4351 is some improvements to the conflict resolution screen (should display the default choice, should allow <kbd>esc</kbd> to cancel)
- #4664 will prevent zooming out from kicking the user back to browse mode

Fix duplicate upload bug, improve upload performance

---

data/address-formats.json

addr:unit is not standard in addressing for France
in France : 800 addr:unit / 4 000 000 addr:housenumber = 0,0002 (0,02%)
This partly reverts https://github.com/openstreetmap/iD/pull/4235/commits/de6b4fb6a20b2a3438b4159192e2b54682fab2e5 in https://github.com/openstreetmap/iD/pull/4235

Restore address format for ["fr", "lu", "mo"]

---

data/address-formats.json

`addr:unit` isn't a common part of addresses in Ukraine 🤷‍♂️

Remove addr:unit for addresses in Ukraine

---

data/presets/fields/ref/isil.json
data/presets/presets/amenity/library.json

I added the `ref:isil=*` tag to the library preset.
Its usage is documented here: https://wiki.openstreetmap.org/wiki/Key:ref:isil

Add ref:isil=* for libraries

---

modules/actions/add_member.js
modules/actions/join.js
modules/actions/split.js
modules/osm/multipolygon.js
modules/osm/relation.js
test/spec/actions/add_member.js
test/spec/actions/join.js
test/spec/actions/split.js
test/spec/osm/multipolygon.js
test/spec/osm/relation.js

Fixes for joining and splitting bugs

---

css/30_highways.css
data/presets.yaml
data/presets/presets.json
data/presets/presets/highway/bus_guideway.json
data/taginfo.json
dist/locales/en.json

There has been no activity for almost 3 weeks on issue #4638, so I picked it up.
I edited the CSS file to get the guideways to look as similar as possible to the picture posted in the issue.
For reference, here is how it looks now
I tried to reuse existing CSS as much as possible and I added oneway to the list of tags suggested in the [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_guideway) to fit the example given.

Added a bus guideway preset

---

css/20_map.css
modules/svg/gpx.js

Add a d3 text for the GPX label's halo and update styles.
It might have been better to follow halo handling as with other labels (roads...). I guess this means a full rewrite of the GPX labels handling. But as the issue was tagged "good first issue" I stick to this simple implementation.
(closes #4617)

Increase GPX labels readability

---

modules/renderer/background.js
modules/renderer/features.js
modules/ui/background.js

This is part of #2864 but I'll split it in multiple PRs. 
I'd like to save/restore the previous background used too, because you can then use "ctrl+b" shortcut to quickly switch between imageries even in a new tab (In France most of us use imagery from BDOrtho IGN instead of Bing but also Cadastre is another great resource to have and we often switch between them).

Restore last imageries used and disable features from local storage

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/amenity/smoking_area.json
data/taginfo.json
dist/locales/en.json

Issue #4701.
I have added a smoking area preset.
I haven't found any fitting icon in the maki set, so I have left the icon field blank. Let me know if using a placeholder such as circle or marker is preferred.

Added smoking area preset

---

modules/ui/map_data.js

Actually area fill was already partly saved in local storage, except for `wireframe` -- I changed logic a bit so that this preference can be saved too.

Restore area fill from local storage including wireframe (Closes #2864)

---

data/presets/categories/barrier.json
data/presets/presets/barrier/kerb.json

Hi there,
I saw issue #4702 and this looked like a good place to get acquainted with the codebase and start contributing. I went ahead and wrote  kerb.json file as well, I was a little unsure of which icon to use so I went with 'wheelchair' from the [maki icon set](https://www.mapbox.com/maki-icons/). 
It might be a good idea to create icons to differentiate between wheelchair friendly and unfriendly barriers. Happy to draft up a proper issue/proposal for that as well n_n
Hope this helps!
-Jason

added support for kerb barrier preset

---

modules/ui/raw_membership_editor.js

In the dropdown for adding the current selection to a relation, each item now has a tooltip showing the same text as the item’s title, handy for situations where the title gets truncated:
This tooltip is similar to the one in the preset and tag editors. It addresses one of the pieces of feedback in https://github.com/openstreetmap/iD/issues/4565#issuecomment-357529846.

Describe relation in tooltip in add membership list

---

data/presets/presets.json
data/presets/presets/amenity/parking.json

closes #4748
I simply removed address from the list of default fields.
The original issue also mentions a preset for multilevel parking that would include the address field and the tag parking=multi-storey. I haven't pushed that change yet because it isn't 100% clear from your comment whether you also want that added. Tell me if I should.

Parking preset: Removed address from default fields

---

data/address-formats.json

The current Polish address fields format includes `addr:place` alongside `addr:street`, which could make it prone to inexperienced users to enter both fileds - and this is, according to [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:addr:place), an error.
This PR simply removes the `addr:place` format. Main discussion on implementing `addr:place` is held under #2898.
Also, the Polish placeholders for `addr:place` and `addr:city` are the same ("Miejscowość"), which only makes more confusion.

Polish Address Format fix

---

data/presets/presets.json
data/presets/presets/historic/wayside_shrine.json

Recently the OpenStreetMap Carto developers wanted to render historic=wayside_shrine (see gravitystorm/openstreetmap-carto#3003 (PR) and gravitystorm/openstreetmap-carto#131 (issue)). The problem was, that only 30% of wayside shrines had a religion tag and therefore a universal icon (for non-christian shrines) became neccessary.
With this PR, mappers can easily add religion and denomination tags to wayside shrines to get a higher religion information coverage for them.

Add religion and denomination fields to wayside shrine

---

modules/services/mapillary.js

If we don't open the image viewer, _mlyViewer is not initialized and when we toggle off the layer, an exception is throw because _mlyViewer is not valid.

do not stop mapillary autoplaying if _mlyViewer is not initialized (closes #4804) 

---

data/presets/presets.json
data/presets/presets/craft/boatbuilder.json

Issue:
When drawing an area and typing "build" in the search bar, "boat builder" is the first result and "building" is only second. This doen't sound like something a user would expect and is a bit annoying when drawing buildings.
Solution:
I changed the match Score of the boat builder preset, "build" now returns building as a first result while "builde" yields boat builder.

reduced search priority for boat builder

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/building/farm_auxiliary.json
data/taginfo.json
dist/locales/en.json

changed farm preset name,
added farm_auxiliary preset

changed farm preset name, added farm_auxiliary preset (#4826)

---

.eslintrc
.flowconfig
build_src.js
modules/util/locale.js
modules/util/session_mutex.js
modules/util/units.js
package.json

This is an initial Proof Of Concept for using flow for https://github.com/openstreetmap/iD/issues/3744.  I've added some annotations to a couple of utils files and updated the build process, including using a rollup plugin to remove the annotations during the build.  The build now runs flow as part of the "run all" script and will report any errors found by flow which will prevent the build continuing.
I've also updated the eslint config to be compatible with the flow annotations, which required use of the eslint-babel parser (see https://github.com/eslint/eslint/issues/2157).  I've used the default config for the https://github.com/gajus/eslint-plugin-flowtype plugin.
If this PR looks ok and is along the lines you were thinking, flow annotations could be added gradually to the rest of …

Start adding flow annotations, plus updates to build and linting processes

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/leisure/dancing_school.json
data/taginfo.json
dist/locales/en.json

This PR adds a preset for _leisure=dance_ with _dance:teaching=yes_. On the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Ddance) _dance:teaching=*_ is described as an additional tag, telling that "dancers can obtain tuition". _dance:teaching_ currently has [over 700 uses](https://taginfo.openstreetmap.org/keys/dance:teaching#overview). Would you accept this tagging scheme and review the structure?

Add preset for dancing school

---

data/presets/presets/amenity/parking.json
data/presets/presets/leisure/pitch.json

added name fields to missing presets leisure=pitch and amenity=parking. #4857

Name fields added to missing presets 

---

modules/behavior/draw_way.js

Fixes #4845 
Can press Esc/Return when cursor is in invalid position and the drawing will still complete
An exception is made for when the completed Area would be invalid (i.e. when a temporarily invalid leading edge has been made as per #4655 , which cannot be accepted as a valid edge when closing the Area)

Can Esc/finish drawing an Area when cursor is in invalid position

---

build_src.js
package.json

Referencing this external issue https://github.com/leebyron/rollup-plugin-flow/issues/5
I have stolen the workaround from [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js/blob/master/build/rollup_plugins.js#L41-L51), thanks to @anandthakker.
(closes https://github.com/openstreetmap/iD/issues/4874)

Use remove-flow-types directly

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/allotments/plot.json
data/presets/presets/landuse/allotments/plot.json
data/taginfo.json
dist/locales/en.json

This PR adds preset for allotments=plot.
Related #4917.

Added preset for allotments=plot.

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/shop/pet_grooming.json
data/taginfo.json
dist/locales/en.json

Refs:https://github.com/openstreetmap/iD/issues/4939

added pet_grooming to shop

---

data/presets.yaml
data/presets/fields.json
data/presets/fields/industrial.json
data/presets/presets.json
data/presets/presets/landuse/industrial.json
dist/locales/en.json

This PR adds a field for industrial=*. It is mainly used for landuse=industrial to describe the type of industry. The key has a [wiki page](https://wiki.openstreetmap.org/wiki/Key:industrial) and [over 23k uses](https://taginfo.openstreetmap.org/keys/?key=industrial#overview) at the moment. Is it okay to add this field?

Add field for industrial=*

---

css/80_app.css
modules/ui/background.js
modules/ui/help.js
modules/ui/map_data.js

Ref. #4599
I have added a button for closing the Background Settings, Map Data, and Help side menus. This is how it looks.
@bhousel @jidanni I have reduced the padding as discussed in the issue, but I think the frontend part can be improved. What do you suggest?

Added button to close Map controls.

---

build_data.js

Gave it a first try.. not quite sure if I covered all combinations in the original json files. I should probably remove those duplicates in `taginfo` as well.
Things like "fields/gender.json" still look pretty strange in the taginfo result. There seem to be some cases, where we don't want a cross product of those string.options values and the keys array.
Supposed to eventually
* fix #4937 
* fix #3598

Add fields to Taginfo file

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/advertising/advertising_column.json
data/presets/presets/advertising/column.json
data/taginfo.json
dist/locales/en.json

I copied `billboard.json` and used this as the base for `column.json`.
I removed the `line` field, since this doesn't make sense for a column. Debating `point`, since a column would have a not-ignorable "width" as well, giving it a shape when looked from above. I left `point` in there nonetheless. It could be used for a thin column, like a tube or pole, though I doubt there are many poles used by advertisers.
Refs:https://github.com/openstreetmap/iD/issues/4961

added column in presets/presets/advertising

---

modules/ui/map_data.js

A quick (possibly temporary) fix for tooltip placement. Currently, the OpenStreetMap data button under the Map Data > Data Layers menu is cut off by the menu heading.

Fixed tooltip location for data layers button

---

data/presets/presets/shop/motorcycle_repair.json

The tag already exists - https://wiki.openstreetmap.org/wiki/Tag:shop%3Dmotorcycle_repair
This could help people tag the POI right.

Add preset for motorcycle_repair

---

modules/ui/raw_tag_editor.js

Implements the behaviour requested in #5024
When a user pastes a string like 'key=value' into the raw tag editor, it gets split into key and value.

Handle key-value pairs pasted as tags

---

data/presets/presets/barrier/retaining_wall.json

The `retaining_wall` behaves the same as a [`hedge`]( https://github.com/openstreetmap/iD/blob/mast/data/presets/presets/barrier/hedge.json), then.
Wiki-Page: https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dretaining_wall
Do you need anything else for this PR?

Add field `heights` to tag for `barrier=retaining_wall`

---

modules/renderer/background_source.js
modules/ui/notice.js

greetings! :wave:
currently OSM editors are requesting roughly 35 million Esri imagery tiles a month 🎉 and making roughly the same number of requests for tiles that don't exist 🚫.
this PR still needs work, but it introduces support for the 'tilemap' option i described in https://github.com/openstreetmap/iD/issues/4327#issuecomment-328198775
the gist of it is that we can take advantage of a service that indicates whether or not tiles exist in a particular area of interest.
by asking whether tiles are present at zoom level 20 in the current extent of the map as soon as the edit session is instantiated, we'd forgo a _lot_ of unnecessary requests for tiles.

use a tilemap for esri imagery instead of tacking on blankTile=false

---

modules/renderer/background_source.js

we actually serve the goods at 5cm in select locations!

use 22 as maxZoom for Esri imagery (selectively)

---

data/presets/presets/playground/swing.json

The capacity defines, if there is one swing on the structure or more. A lot of playgrounds have one structure with two swings on it.
Wiki Capacity https://wiki.openstreetmap.org/wiki/Key:capacity
Wiki Playground https://wiki.openstreetmap.org/wiki/Key:playground (which does not reference capacity)

Add capacity to playground:swing-preset

---

modules/renderer/background_source.js
modules/services/wikidata.js
modules/services/wikipedia.js
test/spec/ui/fields/wikipedia.js

This addresses #5040 by replacing JSONP with XHR where we can, namely:
* Bing imagery metadata access
* Esri imagery metadata access
* Wikipedia API access
* Wikidata API access
The only thing still using JSONP after this is Streetside because that doesn't currently have CORS support as far as I know.

Replace JSONP with XHR where possible

---

css/60_photos.css
modules/services/mapillary.js
modules/ui/init.js

Related to https://github.com/openstreetmap/iD/issues/4930
@bhousel Could you check how to resize Bing StreetSide?

 Add ability to resize to PhotoViewer #4930

---

modules/ui/note_comments.js

fixes #5154 by replacing "-" with "/" in note comment Date strings like "2018-07-05 20:27:09 UTC"

fix browser-specific Date() issues in notes

---

data/core.yaml
dist/locales/en.json
modules/actions/detach_node.js
modules/actions/index.js
modules/operations/detach_node.js
modules/operations/index.js
modules/util/index.js
svg/iD-sprite/operations/operation-detachNode.svg
test/index.html
test/spec/actions/detach_node.js
test/spec/operations/detach_node.js

Hi - I've had an attempt at implementing the Detach Node operation as described in #4320.  I've added the new operation, action & some unit tests for the action.  It will only operate on nodes that are part of at least one way and have at least one tag.  After detaching the node (and replacing with a duplicate without any tags in the way), it switches to move mode immediately so the user can move the detached node.
I'm not sure about the move mode switch, it's not perfect as the mouse pointer is offset from the node based upon the position in the context menu where the Detach Node operation is rendered.
Let me know if you want any changes made!

Add Detach Node operation #4320

---

css/60_photos.css
modules/services/mapillary.js
modules/svg/mapillary_images.js

This PR also leaves visible the directional indicator only for the current image

Update map directional indicator based off of current bearing in MapillaryJS viewer

---

scripts/deploy.sh
scripts/txpush.sh

fixed missing `!` in shellbang. You can check which shell is using with `readlink /proc/$$/exe` in the scirpt. (On my Ubuntu:16.04, it's using `/bin/dash` right now)

Fix shellbang

---

modules/ui/fields/input.js

Fixes #5184 
Seems to be as simple as switching the parseInt to parseFloat when parsing input values.
Only issue is that it allows float values for all tags set using the input box (i.e. 'motorway lanes', which should presumeably just be an integer! Not sure how to avoid this though, without doing something like `type=integer` or `type=float` in the tag presets json files

Allow Float values in height input box

---

css/80_app.css
modules/ui/background.js
modules/ui/custom.js
modules/ui/index.js

Replacing alert box with modal ui

---

modules/renderer/background_source.js

calls to `tilemap` currently fail because i forgot to trim an invalid url parameter when they are constructed.
should be: https://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tilemap/20/550340/621736/8/8

remove ?blankTile=false (and space) from Esri tilemap urls to fix 404

---

data/presets/presets/amenity/language_school.json

Fixes #5245
I had to omit the field for "language" for now, because I could not find a proper way to add it. I guess this functionality has yet to be implemented. If there is already a way, please let me know.

Add preset for amenity=language_school

---

data/presets/presets/man_made/bridge.json

- Added name, bridge type, layer and maxweight fields
- default layer should be set to 1 (like it is for highway=bridge)

Fields and default layer for man_made:bridge

---

data/core.yaml
dist/locales/en.json
modules/util/keepRight/errorSchema.json
modules/util/keepRight/keepRight_error.js

As discussed [here](https://github.com/openstreetmap/iD/pull/5201#issuecomment-417714858), this PR improves the extraction of details from error descriptions by directly using regex group capture instead of splitting the strings and using a lot of logic to figure out what's what (effectively re-implementing the same group capture behaviour).
Advantages of this approach:
- Can precisely extract what we want, no relying on space characters to split the string nicely.
- No need to handle edge cases in the code like this:
https://github.com/openstreetmap/iD/blob/74e06d47472af3c32c8b8012f5b89b5f1af43763/modules/util/keepRight/keepRight_error.js#L66-L73
- Less looping and calls to regex `.test()/.match()` methods.
- We're being more explicit about what we expect in the error strings (aka `\d+` …

[KeepRight] Use regex group capture to extract error details

---

data/presets.yaml
data/presets/presets.json
data/presets/presets/barrier/kerb/lowered.json
data/taginfo.json
dist/locales/en.json

Adds the Lowered Kerb preset

---

data/presets/presets/building/carport.json

Fixes #5339 https://github.com/openstreetmap/iD/issues/5339

Add Carport preset

---

css/80_app.css

Fixes #5373 
Default:
Hover:
I've given it a simple grey styling, but can change it if something else would be better?

Changed styling of "Worldwide search.." button

---

css/50_misc.css
modules/svg/tag_classes.js

Closes #5391. Also: 
- Adds `location` as a secondary tag class
- Adds the `tunnel` styling to lines tagged `location=underground`
Pull the branch and demo at: http://localhost:8080/#background=Bing&disable_features=boundaries&map=18.14/39.90831/-75.21685

Adds custom CSS to man_made=pipeline features

---

data/core.yaml
dist/locales/en.json
modules/ui/raw_member_editor.js

This is a complete version of the very stale #2284. Differences:
- Only individual members can be downloaded, one at a time.
- The map now zooms to relation members selected from the sidebar if they're not visible. This is especially needed since manually downloaded members are often offscreen, but it useful anytime a member is offscreen.
- A download icon is provided.
- Tooltip text is added.
**Hover**
**Downloading**
**Downloaded**
**Selected (zooms to member)**

Adds a button that lets users manually download individual relation members

---

modules/ui/raw_member_editor.js

With #5396 merged, users can now manually download individual members. The issue is that that it is difficult to tell what the member is before it is downloaded. While the member's role is shown in the input field and its index is indicated by its list order, its geometry type is available but hidden. This PR adds the type (node, way, or relation) to the non-downloaded member's label. This should make it slightly easier for users to determine what members to try downloading, as well as surface potential mistakes such as `node` members with `north` or `south` roles.
A potential drawback is that novice users may be confused by the node/way terminology since iD hides it behind points, lines, and areas, but I don't think that novice users will be editing complex relations anyway.

Adds the member geometry type to the label of non-downloaded relation members

---

css/20_map.css
modules/ui/raw_member_editor.js

This lets users see what feature the member refers to before selecting it, reducing the need for guessing.

Adds highlighting of relation members in the map when hovering on their list item

---

modules/ui/selection_list.js

The behavior is the same as the hover highlighting in the relation members list, implemented in #5402.

Adds hover highlighting to the selected features list

---

css/45_waterways.css
modules/svg/tag_classes.js

Closes #5414.
I decided a simple dashed line without casing was the way to go with this one. Ferry routes are often shown this way, and generally the water will provide a nice flat background. I used the cycling path blue because it looked better than the waterway or ditch colors and these features are closer to paths than waterways anyway.

Adds custom CSS styling for ferry routes

---

modules/ui/help.js

Fixes #5439. Additionally fixes the same unwanted behaviour when the buttons on help's navigation pane on the right are pressed.

Fixed using help's navigation buttons not resetting the help pane to the top

---

css/50_misc.css

[location=underwater](https://taginfo.openstreetmap.org/tags/location=underwater#overview) is a lightly-used yet useful tag that could benefit from styling indicating that the features are not visible in imagery.
Example showing both underwater and overhead `power` features with the new styling:

Makes the styling of paths with location=underwater the same as location=underground

---

css/60_photos.css
css/80_app.css
data/core.yaml
dist/locales/en.json
modules/ui/init.js
modules/ui/modes.js
modules/ui/photoviewer.js
modules/ui/save.js
modules/ui/sidebar.js
svg/iD-sprite/icons/icon-sidebar-left.svg
svg/iD-sprite/icons/icon-sidebar-right.svg

**Changes**
- The sidebar can be now be resized by dragging the divider (closes #3447)
- Dragging the sidebar below a minimum size collapses it
- A button in the top toolbar lets you uncollapse the sidebar, complete with icon and tooltip
- Double-clicking the divider toggles the sidebar collapse
- Collapse-toggling is animated
- Selecting a feature or ending an add-feature mode auto-opens the sidebar
- Photoviewer UI has been moved from init.js to photoviewer.js
- The photoviewer now has a slight margin to set it away from the sidebar
- The undo/redo, save, and progress indicator controls are now floated to the right
- The save count has been redesigned to visually integrate with the save button
- When the sidebar is collapsed, the mode buttons are centered
- Full right-to-left layout …

Resizable Sidebar

---

css/80_app.css
modules/ui/raw_tag_editor.js

Previously, the delete and reference buttons in the raw tag editor rows were proportional and expanded when resizing the sidebar. This change saves space and makes these buttons constant with others in the editor by keeping them a fixed-width.

Keeps the raw tag editor buttons fixed-width using flexbox

---

data/core.yaml
dist/locales/en.json
modules/modes/drag_node.js

Adds undo messages for connecting:
- Points to points, vertices, lines, and areas
- Vertices to sibling and adjacent vertices (nodes with the same parent way)
Closes #1252.

Expanded undo messages for node-dragging scenarios

---

css/80_app.css
data/core.yaml
data/shortcuts.json
dist/locales/en.json
modules/geo/extent.js
modules/modes/select_data.js
modules/modes/select_note.js
modules/renderer/map.js
modules/services/mapillary.js
modules/services/openstreetcam.js
modules/services/streetside.js
modules/ui/background.js
modules/ui/confirm.js
modules/ui/help.js
modules/ui/init.js
modules/ui/map_data.js
modules/ui/modes.js
modules/ui/photoviewer.js
modules/ui/save.js
modules/ui/settings/custom_background.js
modules/ui/settings/custom_data.js
modules/ui/sidebar.js
modules/ui/undo_redo.js

closes #4356
- Makes the "Sidebar" toggle button permanent but removes the label
- Did some things to the "Save" button to make it the same width whether there
is a count or not (prevents the buttons from jumping when pressing undo/redo)
- Removes a lot of the floated col rules that aren't used much anymore
I'd like to figure out collapsing away the labels and leaving only icons on very narrow screens.  
(I know I can use a media query for this)

Flexbox buttons in top bar

---

css/20_map.css
css/70_fills.css
modules/modes/drag_node.js
modules/presets/index.js
modules/renderer/map.js
modules/svg/areas.js
modules/svg/helpers.js
modules/svg/index.js
modules/svg/labels.js
modules/svg/layers.js
modules/svg/lines.js
modules/svg/midpoints.js
modules/svg/osm.js
modules/svg/points.js
modules/svg/touch.js
modules/svg/turns.js
modules/svg/vertices.js
modules/ui/fields/restrictions.js
modules/ui/init.js
test/spec/behavior/select.js
test/spec/svg/layers.js
test/spec/svg/osm.js

This adjusts the stacking order so that the interactive OSM objects take precedence over the interactive non-OSM objects.
fixes #5257
Still need to test a bit more..

Layer adjustments

---

css/80_app.css
modules/ui/field.js
modules/ui/fields/access.js
modules/ui/fields/cycleway.js
modules/ui/fields/input.js
modules/ui/fields/localized.js
modules/ui/fields/radio.js
modules/ui/raw_member_editor.js
modules/ui/raw_membership_editor.js
modules/ui/raw_tag_editor.js
modules/ui/tag_reference.js

Closes #5473.
This goes beyond the scope of the original issue by applying flexbox to all of the `.form-field` elements. This lets us remove lots of specialized float, clearfix, and position absolute hacks.

Flexbox preset field, member, and membership UI

---

modules/renderer/map.js

Closes #5508.
I didn't end up piggybacking on the Control key zooming since that has an extra scale multiplier for the pinch-to-zoom.

Trackpad scroll-to-zoom while holding Shift or Option/Alt

---

css/50_misc.css

This PR adds special rendering for attraction=water_slide. I've used the color for the water slide stroke from OpenStreetMap Carto and it looks like this:

Add rendering for attraction=water_slide

---

css/20_map.css
modules/osm/tags.js
modules/osm/way.js
modules/svg/defs.js
modules/svg/helpers.js
modules/svg/index.js
modules/svg/lines.js
test/spec/osm/way.js
test/spec/svg/lines.js

This generalizes the oneway arrow logic for adding SVG markers along a
line. Using that functionality, certain tags get arrows on their
right-hand side, indicating which side is "inside", e.g. the
right-side of a cliff is the lower side.
The list of tags considered to be sided (unless there's a
two_sided=yes tag) is:
- natural=cliff
- natural=coastline
- barrier=retaining_wall
- barrier=kerb
- barrier=guard_rail
- barrier=city_wall
- man_made=embankment
The triangles attempt to be reminiscent of the triangles used for
rendering cliffs on OSM (and elsewhere). The different tags get
different renderings (e.g. colors that match the main way, and
different spacings). In addition, natural=coastline is special-cased
to have blue markers (despite having a green way), to emphasise that
the …

 Add one-sided triangular markers to ways with sides (e.g. natural=cliff).

---

modules/ui/fields/restrictions.js
modules/ui/init.js
modules/ui/sidebar.js

Fixes #5474 
I've put together a bit of a hacky fix for the restrictions editor not scaling properly with the sidebar being dragged.
Ideally, I'd call the `redraw()` method direction from the sidebar's drag handler, but can't figure out a way to get access to it efficiently, so instead I just add a `dragging` class when the drag starts and remove it when it stops.
The restrictions.js file then just sets a `setInterval` that checks whether the `dragged` class is present or not, and then redraws the panel every 50ms if it is.
The redraw interval can be changed easily enough (is 50ms too frequent?), but when dragging, the street graphics are chopped off so close to the border of the svg, that when dragging, the chopped-off street edge is still visible for a few ms until the panel redraws. …

Redraw restrictions panel when dragging sidebar

---

modules/ui/intro/intro.js

Fixes #5553.
The crash was due to the `touch` layer not having an `enabled` function. Since we always want the touch layer enabled, I just added a check to make sure the `enabled` function exists before calling it.

Fixes an issue where the walkthrough would not display and cause an error

---

dist/locales/en.json
modules/core/history.js
modules/services/maprules.js
modules/ui/commit_warnings.js
modules/ui/issues.js
modules/validations/deprecated_tag.js
modules/validations/disconnected_highway.js
modules/validations/index.js
modules/validations/many_deletions.js
modules/validations/mapcss_checks.js
modules/validations/missing_tag.js
modules/validations/old_multipolygon.js
modules/validations/tag_suggests_area.js
modules/validations/validation_issue.js

1. Add a class to represent the validation issue
2. Extend the data model for an validation issue to
(1) add a severity level field (useful for identify save-blocking issues later)
(2) replace single entity with an array of entities (useful for issues involving multiple entities)
(3) add a coordinates field for highlighting the location of the issue on the map
(4) add a fixes field for possible automatic fixes
3. Update existing validation modules to use the new data model

Extend data model for validation issues

---

test/spec/actions/split.js

I've added some tests for the splitting of route relations containing loops as described in bug #4876 
There are probably too many combinations of ways directions, loop traversal direction to test them all, but I can add more combinations if it's helpful.

Add more tests for splitting ways in relations containing loops

---

modules/svg/geolocate.js
modules/svg/index.js
modules/svg/layers.js
modules/ui/geolocate.js
test/spec/svg/layers.js

the 'puck' radius is geolocation response's [accuracy (in meters)](https://w3c.github.io/geolocation-api/#dom-coordinates-accuracy)
closes #5587

5587 - make geolocation show geolocation

---

modules/osm/entity.js
modules/ui/inspector.js
modules/ui/preset_list.js
modules/ui/sidebar.js
test/spec/osm/entity.js

Old behavior: The preset list is shown when selecting a feature without tags (except `area=yes`) and that is not member of a relation. Otherwise show the editor.
New behavior: The preset list is shown when selecting a new feature or a `vertex` without tags. Otherwise show the editor.

Change the initial inspector of the sidebar upon feature selection

---

modules/util/detect.js

With the hash-url `locale=en-US` or `locale=de-DE` one can force a locale and language regardless of the given language from the osm-website-settings.
This is to solve https://github.com/openstreetmap/iD/issues/5644.
However, while looking into this I understood that the interface language is in fact pulled from the OSM-website-profile-language (not the browser language). So there is a way to change the language, by editing the preferred languages in the profile.
So while this PR makes changing the language a bit easier and quicker, I am not sure if it is worth the added complexity.
In case this should be continued, those thinks are todo IMO:

Allow locale and language being set via URL param

---

data/core.yaml
dist/locales/en.json
modules/services/index.js
modules/services/osm_wikibase.js
modules/ui/tag_reference.js
test/index.html
test/spec/services/osm_wikibase.js

This completes the work by @bhousel (thanks for getting me started!)
* Takes data directly from the Wikibase data items (OSM Wiki)
https://wiki.openstreetmap.org/wiki/OpenStreetMap:Data_Items
* Understands the difference in regions - e.g. will show different
images depending on the local settings
* Perf: Single request will get both the tag and key description
* Slightly different wording to encourage description editing/translation
| RU has a custom image | EN has no image |
|-----|-----|
| ![image](https://user-images.githubusercontent.com/1641515/50370998-52865980-0580-11e9-96f7-23452d5b40f0.png) | ![image](https://user-images.githubusercontent.com/1641515/50371015-ad1fb580-0580-11e9-9fc3-38879c588ce7.png) |

OSM Multilingual data directly from wiki (wikibase data items)

---

modules/ui/combobox.js

closes #5618
I reproduced by adding a part, and in raw tag editor and `ca` as value for key `natural`.
Now, it should accept that input rather than setting it to `cave_entrance` or removing the input entirely...

fix autocomplete combobox bug

---

modules/ui/keepRight_details.js

Capitalize the first letter of the KeepRight error detail, specifically for detail strings that could begin with a placeholder string. For example, in Vietnamese, the following strings begin with a placeholder string denoting a type of element:
* `QA.keepRight.errorTypes.<60>.description`
* `QA.keepRight.errorTypes.<70>.description`
* `QA.keepRight.errorTypes.<74>.description`
* `QA.keepRight.errorTypes.<75>.description`
* `QA.keepRight.errorTypes.<100>.description`
* `QA.keepRight.errorTypes.<190>.description`
* `QA.keepRight.errorTypes.<200>.description`
* `QA.keepRight.errorTypes.<220>.description`
* `QA.keepRight.errorTypes.<221>.description`
* `QA.keepRight.errorTypes.<232>.description`
But the same placeholder string can be inserted mid-sentence into …

Capitalize first letter of KeepRight error detail

---

data/core.yaml
dist/locales/en.json
modules/validations/highway_almost_junction.js
modules/validations/index.js
modules/validations/validation_issue.js
test/index.html
test/spec/validations/highway_almost_junction.js

but avoid connect when the edge goes in parallel to the other road.
also added tests for the validation.

add validation for connecting highway with extension

---

css/80_app.css

This will center `.geocode-item` in rtl mode.

fix for first part of #5687

---

modules/ui/edit_menu.js

[RTL] place tooltip under #id-container to inherit rtl

---

data/presets/presets/office/estate_agent.json

Presets: Add alias of "real estate" for estate agent

---

modules/renderer/background_source.js
test/spec/renderer/background_source.js

Added support for `{wkid}`, `{w}`, `{s}`, `{n}`, and `{e}` tokens in WMS-style background imagery templates, as described in [this JOSM documentation](https://josm.openstreetmap.de/wiki/Maps#WebMapServicesWMS).
The `{wkid}` token is particularly handy for `exportImage` endpoints in ArcGIS ImageServer services. (In fact, it appears multiple times, whereas the previous code only replaced each token once.) Currently, osmlab/editor-layer-index#611 works around the lack of this token by hard-coding a projection, but JOSM can use the `projection` property correctly: https://github.com/osmlab/editor-layer-index/commit/95680b2a3b9f468748365deb37943c7f1f871955#r31964799. Once this PR lands, we can modify the editor layer index’s tests to accept `{wkid}` as an alternative to `{proj}`.
Thanks to …

Replace wkid/w/s/n/e in WMS URL templates

---

modules/actions/reverse.js

Closes #5674 
Couldn't think of any other keys where left/right value is relative to the key and not the way direction.

Fix turn:lanes changing when way is reversed

---

css/60_photos.css
modules/services/mapillary.js
modules/services/openstreetcam.js
modules/services/streetside.js
modules/svg/mapillary_images.js
modules/svg/mapillary_signs.js
modules/svg/openstreetcam_images.js
modules/svg/streetside.js

Closes #5494 
~~So the cause of that issue was that whenever the svg layer `update()` method was triggered the "selected" and "highlighted" classes which get added by method `setStyles()` in the service are not being retained. The simple fix here is to just re-apply `setStyles()` with every update (there's likely a nicer way to just preserve them in the first place).~~
Since found to be false. See my comments below.
In testing, further issue with the interaction between multiple active street imagery layers was discovered. This turned out to be because the `reset` parameter of `setStyles()` was being used for style updates due to svg layer events (as far as I can see it is only needed for style updates due to interaction with the viewport - where the selected bubble/sequence is changed …

Fix street imagery hover and selection behaviour

---

dist/locales/en.json
modules/actions/join.js
test/spec/actions/join.js

Implements intersection check, as raised in #4745

Add check to stop joining ways if resulting way intersects itself

---

.gitattributes

Running "npm test" currently spews out many eol errors if you don't have git configured not to convert line endings to crlf.
As I understand it this change should override that (see: https://help.github.com/articles/dealing-with-line-endings/).

Update .gitattributes to use lf eol for .js files

---

data/core.yaml
dist/locales/en.json
modules/services/improveOSM.js
modules/ui/improveOSM_details.js

See https://github.com/openstreetmap/iD/pull/5739#issuecomment-460786055
This is something of a temporary solution as error titles and descriptions will be pretty easily generalised so the UI code is likely to change.

Fix negative number of trips in ImproveOSM issues

---

css/80_app.css
data/core.yaml
dist/locales/en.json
modules/renderer/features.js
modules/ui/preset_list.js

Closes #5876.
It'd be great to get a review since this changes some rather hot code.

Disable preset buttons for hidden layers

---

modules/modes/move.js
modules/modes/rotate.js

Allows these operations to be performed on entities that are forced visible without them disappearing during the move/rotation.

Persist forced visible entities on move/rotate

---

modules/behavior/draw_way.js

Fix pressing Escape with only one active node in area

---

data/deprecated.json

https://taginfo.openstreetmap.org/keys/building%3Acolor
inspired by https://josm.openstreetmap.de/browser/josm/trunk/data/validator/deprecated.mapcss#L569

building:color -> building:colour deprecation

---

data/core.yaml
dist/locales/en.json
modules/actions/orthogonalize.js
modules/core/difference.js
modules/geo/index.js
modules/geo/vector.js
modules/operations/orthogonalize.js
modules/osm/way.js
modules/ui/intro/helper.js
test/spec/actions/copy_entities.js
test/spec/actions/orthogonalize.js
test/spec/core/difference.js
test/spec/geo/vector.js

This PR fixes several long-standing issues with the orthogonalization action.

Improve orthogonalization action

---

API.md

I tried to make the documentation a bit more specific since I ran into this at https://github.com/openstreetmap/iD/issues/5988.
_Changes:_
- Highlight the different URL param-patterns (hash vs. regular)
- Add an example with regional locale `en-US`
- Add `locale` param to the list of osm-website-params with a bit more info about the different default-behavior there
This is a follow up to https://github.com/openstreetmap/iD/pull/5650 and based on the feedback in https://github.com/openstreetmap/iD/issues/5988. Thanks @quincylvania for https://github.com/openstreetmap/iD/commit/07327eb9c7d138c70c1b96fdcad261c921e1cf00, btw.

Clarify API.md description for `locale` param

---

modules/util/svg_paths_rtl_fix.js
package.json

Long time no see! Good news: I have updated my workaround for Arabic road labels in Chrome! (updated text below as I test the problem)
Current broken label in Erbil at real and magnified size (expected: شەقامی کوردستان )
This label helped me understand what was unnoticed or broken by Chrome since our earlier fix. The first/rightmost two letters شە get broken off and reattached to the end/left of the label, even though there is no whitespace char there? This is strange and happens on other road labels and letters.
In December I published <a href="https://github.com/Georeactor/alif-toolkit">alif-toolkit</a> with a JSON structure of all Arabic Unicode presentation forms. This replaces our old array with a more comprehensive list. I am investigating exactly what else should happen next (is it …

Fix Arabic script road labels on Chrome

---

modules/util/svg_paths_rtl_fix.js
package.json

Correcting an error from previous PR, where Eastern Arabic numerals ( ० ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹ ) were being marked as undefined and/or being reversed order

Patch Arabic numerals

---

package.json

Don't feel like tracking down whatever `getOwnPropertySymbols` thing is breaking PhantomJS right now.

fix: pin sinon to 7.2.7

---

data/discarded.json

There is currently ongoing discussion on talk mailing list about my proposed automatic edit that proposed to remove it.
It seems to be that there is a consensus to eliminate this tag (as unwanted rendering instruction for no longer existing renderer), but not everybody is happy about using bot edits. It was proposed to silently discard it during editing like created_by tag.
JOSM added this tag to list of automatically discarded ones - see https://josm.openstreetmap.de/changeset/14916/josm
See https://wiki.openstreetmap.org/wiki/Key:osmarender:nameDirection (note, I recently changed it), https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/elimination_of_osmarender:nameDirection and https://lists.openstreetmap.org/pipermail/talk/2019-March/082280.html thread …

Add osmarender:nameDirection to discarded tags

---

modules/validations/incompatible_source.js

Updates the fix for #6135 and just adds a loop that loops through a list of invalid sources

Allow for multiple invalid sources

---

modules/actions/disconnect.js
modules/operations/disconnect.js
test/index.html
test/spec/actions/disconnect.js

This adds to the fix in #6149 and makes it so that when a closed way is selected as well as the node to disconnect, the closed way gets disconnected from anything it is connected to, but remains closed.
I think this stay truer to the existing functionality where when a way is selected, the way is disconnected independently and every other connection remains as it was. Chances are that the user just wants to disconnect the closed way from the junction node, rather than opening up the way as well (which they can just do after if that was actually their intention)
If they _do_ want to disconnect everything at the junction node, they can just right click the node without selecting any connected ways, and everything will be disconnected as usual.
I've also added a fix so that the option to …

Leave way as closed when disconnecting

---

modules/ui/raw_tag_editor.js

As requested by @tordans in #5070 and #6185:
When pasting multiple tags like "amenity=restaurant name=The Restaurant", they shall be split up and added separately. My implementation assumes that there will never be spaces in keys, so it also handles cases like "name=The Restaurant amenity=restaurant" correctly, and splits it up at the last space before the key.

Handle multiple tags when splitting up in tag editor

---

data/presets/presets/aerialway/j-bar.json

I noticed that from the `aerialway` presets, `j-bar`, described in the wiki as a type of `aerialway=drag_lift` seems to be missing. T-bar already exists in the presets.
https://wiki.openstreetmap.org/wiki/Tag:aerialway%3Dj-bar

Add aerialway=j-bar to presets

---

data/deprecated.json

Also deprecated in the wiki and a replacement is available, see https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Ddancing_school

Deprecate amenity=dancing_school

---

data/presets/presets/man_made/beacon.json

Used about 8k times. Documentation defines this a little wide:
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbeacon
In other words, could be any kind of beacon, a [daybeacon](https://en.wikipedia.org/wiki/Day_beacon), a [light (beacon)](https://en.wikipedia.org/wiki/Leading_lights), even an aeronautical beacon. This is why I put `matchScore: 0.5`, so that a match does not possibly shadow the more exact presets with the various `seamark:type`s.

add man_made=beacon preset

---

data/presets/presets/shop/general.json

The tag is used 2800+ times and following a recent discussion on the tagging mailing list, the tag is pretty well documented now and also what is the difference to `shop=convenience`, `shop=variety_store`, `shop=department_store`, `shop=hardware` and `shop=doityourself` and so on.
See https://wiki.openstreetmap.org/wiki/Tag:shop%3Dgeneral
Also, there is a good wikipedia article about it: https://en.wikipedia.org/wiki/General_store

Add shop=general for general store

---

data/presets/presets/aeroway/hangar.json
data/presets/presets/building/hangar.json

Also, make the hangar building preset have a lower matchScore so that first the` aeroway=hangar` is found. Add `building=hangar` to the aeroway preset.
See https://wiki.openstreetmap.org/wiki/Tag:building%3Dhangar

Add preset for building=hangar

---

data/presets/fields/self_service.json
data/presets/presets/amenity/car_wash.json
data/presets/presets/amenity/fuel.json
data/presets/presets/shop/laundry.json
data/presets/presets/shop/laundry/self_service_laundry.json

Added the laundromat preset because it often has quite a different name in languages (including English) than a generic (staff-operated) laundry. See https://en.wikipedia.org/wiki/Self-service_laundry
Also, added the `self_service` field https://wiki.openstreetmap.org/wiki/Key%3Aself_service , used 7k+ times and added this field to the presets that often have self-service: fuel stations, car washes and laundries. Not sure if it should be in `fields` or `moreFields`.

Added laundromat preset and self_service field

---

data/deprecated.json

Jewellery is the British English name for a jewelry. Usually in OSM, we use British English for tag names, but in this case the American English name established itself. Jewellery is now marked as deprecated in the wiki. See
https://wiki.openstreetmap.org/wiki/Tag%3Ashop%3Djewellery and
https://wiki.openstreetmap.org/wiki/Tag%3Ashop%3Djewelry
There are now a few hundred places left which are tagged with jewellery. A deprecation in iD helps to reduce this and accidental mistaggings as `jewellery` in the future by people who simply input the British English name as we usually do.

deprecate shop=jewellery

---

data/core.yaml
dist/locales/en.json
modules/ui/inspector.js
modules/validations/dupe_node_on_road.js
modules/validations/index.js

Addresses issue #6241
Also made a change in inspector, so that when an untagged entity has issues, entity editor is shown to make the issues visible. Otherwise it's a confusing experience for users when they click on an item on the issues pane but don't see the issue show up in the inspector.
Using a cheap check by delta on lat/lon degrees, since 1-e5 degree is ~1 meter. Let me know if the great-circle geo-distance is preferred.
Tested in browser and see the issue gets flagged; also verified the merge operation works.
cc @wonga00 @chrisklaiber

add validation for very close node on road

---

data/presets/presets/tourism/artwork/bust.json
data/presets/presets/tourism/artwork/graffiti.json
data/presets/presets/tourism/artwork/installation.json

Added the next three most used (according to taginfo) artwork types: Graffiti, Installation and Bust.
I think it is important to
* have bust if statue exists as a preset
* have graffiti if mural exists as a preset
* and have installation if sculpture exists as a preset
to avoid mistaggings, e.g. people searching for "graffiti wall" and finding only the "mural" preset would probably tag it (incorrectly) as a mural. Same with the others

Add bust, graffiti and installation artwork type preset

---

data/presets/presets/building/houseboat.json

[Documented since 2014](https://wiki.openstreetmap.org/wiki/Tag%3Abuilding%3Dhouseboat), used 14k+ times.

add houseboat preset

---

dist/index.html

There are multiple calls to the favicon on the preview.ideditor.com system in one session:
> GET http://preview.ideditor.com/favicon.ico 403 (Forbidden)
According to https://stackoverflow.com/questions/1321878/how-to-prevent-favicon-ico-requests#comment50777781_13416784 this should show an empty favicon which will prevent the browser to try loading the missing icon.
- Is this the right index.html file that is used for the preview build?
- Is this the smart way to solve this? – Please just close it otherwise :).

Add an empty favicon for preview.ideditor.com

---

dist/index.html

It looks like it is more than 6 years old https://github.com/openstreetmap/iD/blame/372bb7d892048d67415087f474688f85391bab2a/dist/index.html#L28 and the linked URL seems to be broken:
> $ curl http://dnn506yrbagrg.cloudfront.net/pages/scripts/0013/6714.js
> "undefined"==typeof CE2&&(CE2={}),CE2.uid=136714,CE2.status="no data available";
So to me it looks like it is save to remove it(?)

Remove crazyegg from the preview-index.html

---

data/presets/presets/tourism/zoo/petting.json
data/presets/presets/tourism/zoo/safari.json
data/presets/presets/tourism/zoo/wildlife.json

- add [**petting zoo**](https://wiki.openstreetmap.org/wiki/Tag:zoo%3Dpetting_zoo) preset, documented since 2009, used ~600 times. A children's zoo with farm animals.
- add [**wildlife_park**](https://wiki.openstreetmap.org/wiki/Tag:zoo%3Dwildlife_park) preset, documented since 2017, used ~180 times. A zoo with indigenous animals in natural environment.
- add [**safari_park**](https://wiki.openstreetmap.org/wiki/Tag:zoo%3Dsafari_park) preset, documented since 2017, used only ~24 times. A drive-through zoo with exotic animals.
The wildlife park seems to be mostly unknown in the USA / United Kingdom, but it is a thing in Germany, Austria, Switzerland ([**Wildpark**](https://de.wikipedia.org/wiki/Wildpark)), France (**Parc de vision**), Netherlands (**Wildpark**), Israel (**חי-בר**) maybe …

add some zoo types presets

---

data/deprecated.json
data/presets/presets/craft/agricultural_engines.json
data/presets/presets/craft/floorer.json
data/presets/presets/craft/joiner.json
data/presets/presets/craft/parquet_layer.json

Add a few craft presets:
- [**joiner**](https://wiki.openstreetmap.org/wiki/Tag%3Acraft%3Djoiner), documented since 2014, 600+ usages. A joiner is someone who builds furniture. There is also [`craft=cabinet_maker`](https://wiki.openstreetmap.org/wiki/Tag%3Acraft%3Dcabinet_maker) (200 usages) but I did not include that in this PR because it is not clear what is the difference to a joiner.
- [**agricultural engines mechanic**](https://wiki.openstreetmap.org/wiki/Tag%3Acraft%3Dagricultural_engines), documented since 2011, 500+ usages. I am not sure if this is the right word in English, in German it is [Landmaschinenmechaniker](https://de.wikipedia.org/wiki/Landmaschinenmechaniker)
- [**parquet layer**](https://wiki.openstreetmap.org/wiki/Tag:craft%3Dparquet_layer), documented since 2011, ~80 …

add joiner, floorer, agricultural engine mechanic and parquet layer crafts

---

data/presets/presets/emergency/fire_hose.json

[Documented in the wiki](https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dfire_hose) since 2010, used 0.9k times.

add preset for fire hose

---

data/presets/presets/natural/water/wastewater.json

A settling or clarifying basin for wastewater. Used 17+k times and [documented in the wiki](https://wiki.openstreetmap.org/wiki/Tag:water%3Dwastewater).
Usually found in a wastewater plant, but on the countryside, it may also look like an innocent pond (if there are no signs).
I am not sure if I hit the correct English name here, I did not find a wikipedia article that is only about the basin, not the whole wastewater plant.

add preset for water=wastewater

---

data/presets/presets/natural/rock.json

... which is actually more precisely a free-standing (large) [boulder](https://en.wikipedia.org/wiki/Boulder). Already **used a whopping 156+k  times** and [documented in the wiki](https://wiki.openstreetmap.org/wiki/Tag:natural%3Drock).
Useful for orientation and interesting for climbers.
There is also `natural=stone`, used 14+k times, also [documented in the wiki](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dstone), but not included in this pull request. It is documented to be a type of boulder, **one which is not attached to the underlying bedrock**. These often arrived at their current place through glaciation. In English, this type of boulder is called a [glacial erratic](https://en.wikipedia.org/wiki/Glacial_erratic).
If you wonder why there are these two tags at all, this is …

Add preset for natural=rock

---

data/presets/presets/barrier/sally_port.json
data/presets/presets/historic/castle/fortress.json
data/presets/presets/historic/castle/palace.json
data/presets/presets/historic/castle/stately.json
data/presets/presets/historic/city_gate.json
data/presets/presets/historic/fort.json
data/presets/presets/historic/manor.json
data/presets/presets/man_made/cross.json
data/presets/presets/natural/water/moat.json

- [`man_made=cross`](https://wiki.openstreetmap.org/wiki/Tag%3Aman_made%3Dcross), documented since 2011, used 4600+ times. This is a "cross of no religious or historic importance", so, usually a **summit cross**.
- [`water=moat`](https://wiki.openstreetmap.org/wiki/Key:water), documented since 2013, used 400+ times
- [`historic=city_gate`](https://wiki.openstreetmap.org/wiki/Tag%3Ahistoric%3Dcity_gate), documented since 2010, used 3000+ times
- [`barrier=sally_port`](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dsally_port), documented since 2012/2016, used 4000+ times, approved. A side gate or **postern** in castles, e.g. for sorties.
- [`historic=fort`](https://wiki.openstreetmap.org/wiki/Tag%3Ahistoric%3Dfort), documented since 2012/2016, used 3500 times
- …

add castle-related presets

---

data/core.yaml
dist/locales/en.json
modules/validations/disconnected_way.js
test/spec/validations/disconnected_way.js

This addresses issue #5869. 
(This code was originally by @gaoxm- Thanks Ming!) 
Old behavior: mappers could create new highways that didn't attach to any existing highways. If the new highways were all connected to each other, no warning flag would present itself. 
New behavior: mappers will receive a warning if they create any new highways that aren't ultimately connected to existing ones. 
Validation catching two new connected primary (orange) highways that are otherwise disconnected from the rest of the highways: 
Issue is no longer flagged when the two new highways are connected:

Improve validation for disconnected highways #5869

---

data/presets/presets/barrier/chain.json

**Used 11000+ times** and documented since 2009 (on own page since 2011)
See https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dchain
The problem maybe is that the name "chain" is perhaps too broad so it might be mistaken for something else? Suggestion: "Chain Barrier"?

add barrier=chain preset

---

CHANGELOG.md
data/core.yaml
dist/locales/en.json
modules/validations/disconnected_way.js
modules/validations/impossible_oneway.js
test/spec/validations/disconnected_way.js

This upgrades the disconnected ways validation to flag entire routing islands as single issues.
It also incorporates ferry routes as first-class routable ways. This means ferry routes can resolve or extend routing islands and that disconnected ferry routes are flagged.
Routable ways are considered connected to the larger network if they connect to building entrances or parking garage entrances, or overlap unloaded tiles.
The code could be made more efficient eventually but it's okay for now.
@bhousel please give it a lookover and merge when ready. Make any changes you need.

Flag routing islands

---

data/deprecated.json

The correct way to tag a tanning salon is a beauty shop that offers
tanning as a service.
Signed-off-by: Tim Smith <tsmith@chef.io>

Deprecate leisure/tanning_salon

---

data/core.yaml
dist/locales/en.json
modules/validations/index.js
modules/validations/invalid_format.js

Closes #5866
Simple validation following the HTML5 standard for emails as we don't expect POIs to have convoluted email addresses (so there should be minimal false positives). For websites I'm only checking that the scheme is present currently. 
Only checks the `website` and `email` tags as these are what iD currently supports with fields.
I was unsure how best to handle the `reference` property for the `validationIssue` objects because both issues can be present at once on the same entity (so using one function and changing the text via variable isn't viable). Just defined two functions for now since it works, can be refactored as desired.
The main thing to get right here are the translated strings. I think the website one should probably be reworded as it can flag instances where the …

Add email and website format validation

---

modules/validations/invalid_format.js

Issue raised by https://github.com/openstreetmap/iD/pull/6494#issuecomment-499620002.
I just modified the regex to instead use negated lists for characters which can only appear inside a quoted string email address (the likelihood of a POI - or anyone - using such an email is minuscule). The other option would have been to put Unicode character ranges inside the square brackets, but this way means we don't accidentally exclude any more valid characters.
Also fixes handling for list values with excess whitespace by stripping it out.

Fix email validation for Unicode characters

---

modules/ui/tools/structure.js

Fixes #6559 
Way is rejoined back to a single way if structure change is reverted

Rejoin way if structure choice is reverted

---

css/80_app.css

I was testing out OSM iD V3 (awesome, by the way! 😎) and I noticed that the trash button has a border-radius on both left and right sides in right-to-left language layout.  Quick fix

Minor CSS fix

---

data/presets/presets/amenity/vending_machine/bottle_return.json

This might be useful as a preset, as, at least in Germany, every store that sells bottles also has to provide a machine to return those bottles. (There is even a law for that 😄: https://www.gesetze-im-internet.de/verpackg/__15.html)
The current usage in OpenStreetMap is actually rather low (below 100), but maybe this increases when there is a preset for this machine...

Add vending=bottle_return preset

---

modules/validations/generic_name.js

Currently a generic name warning can be given for a known brand (see http://preview.ideditor.com/master/#background=Bing&id=n6573433998) and this fixes that.
I figure it makes sense for an entity with a regular wikidata tag too which is why I've used `hasWikidata`.

Fix generic name validation for known brands

---

data/core.yaml
dist/locales/en.json
modules/ui/background.js
modules/ui/info.js
modules/ui/init.js

This reorganizes the detailed background buttons for #6397 and #6820.
I'm opening this PR since I know exposing advanced UI like this has been controversial in the past. I for one think it's worth making this panel more discoverable and mobile-friendly.

Add button to toggle the Background info panel

---

modules/ui/tools/quick_presets_recent.js

Closes #6888.
When Geometries is toggled off they are visible in Recents.
When Geometries is toggled on they are filtered out of Recents.

Filter out generic tools in recents

---

css/20_map.css
modules/svg/defs.js

Cliffs had their colour changed in 5f9bea67d, but the directional
arrow remained green.
Fixes #6918

Change cliff direction marker to dark grey to match the line

---

modules/services/mapillary.js

Changed Mapillary API URLs to include a parameter enabling pagination to fix a bug with missing traffic signs, and also changed a parameter indicating minimum number of photos a traffic sign must be visible in before being vision as a point feature (from 1 previously to 2 now).

fix: mapillary pagination and minimum detection count

---

README.md

Changed the urls linking to the preview branch from http to https to avoid an automatic redirect to the https version.
Sorry for my mistake earlier!
(Redid https://github.com/openstreetmap/iD/pull/6983#event-2748966721 on the correct branch)

Updated readme urls to https to avoid redirect [v2]

---

data/presets/presets/shop/spices.json

This adds a preset for [`shop=spices`](https://wiki.openstreetmap.org/wiki/Tag%3Ashop%3Dspices).

Add preset for `shop=spices`

---

data/core.yaml
modules/validations/crossing_ways.js

This concerns issue [#6617](https://github.com/openstreetmap/iD/issues/6617) . When user clicks on "Use a bridge"/"Use a tunnel" it splits edge if is long and creates bridge/tunnel. Later user may correct bridge/tunnel location by manually shifting nodes.

Fix issue #6617

---

modules/ui/entity_editor.js

An easier way to recreate the issue is by creating two ways of different type then select both and undo one of the lines. This patch removes the removed selected ids from the editor by manipulating _entityIDs in historyChange().

fix issue #7090

---

modules/util/svg_paths_rtl_fix.js

Fixes #7104 where in Chrome-based browsers, road labels with Arabic + Latin script, the Latin letters were reversed
Previous code had two different paths for Arabic and other RTL languages. Now putting them in one flow, adding more Arabic codepoints, adding more numeral codepoints (numerals are in Arabic Unicode ranges, but flow LTR)

Arabic + Latin combined labels

---

modules/ui/fields/combo.js

#5728
Drag and drop working fine on full-width tags i.e. `Destination` but slightly different for the other inputs e.g. `Destination Road Numbers`. Please can I get some opinions on the code and the functionality
Questions:
1) Am I supposed to have added tests?
2) Am I supposed to have added documentation? It would make sense to have it somewhere when the `i` button is clicked
3) Is this the correct place to put this code? Its similar functionality to the drag and drop for [relations](https://github.com/openstreetmap/iD/issues/5728#issuecomment-490910699). But seems a bit premature to abstract it out.
4) I haven't looked into testing mobile - is this something that iD supports?
5) I am trying to merge to master - not sure if this is correct as I've branched from `2.x` . Is master version …

Drag and drop of semicombos

---

css/80_app.css
data/core.yaml
dist/locales/en.json
modules/modes/select.js
modules/ui/entity_editor.js
modules/ui/inspector.js
modules/ui/preset_list.js
modules/ui/raw_tag_editor.js
modules/ui/selection_list.js
modules/ui/sidebar.js
modules/util/array.js
modules/util/index.js
test/spec/ui/raw_tag_editor.js

This brings the multiselect tag editing (#1761) from `master` to `2.x`. There's no real reason this feature has to wait for the v3 UI.
It's not done yet but I wanted to get a PR drafted before the week was out.

Raw tag editor for multiple select features (2.x)

---

data/core.yaml
dist/locales/en.json

See https://github.com/openstreetmap/iD/pull/7095#issuecomment-570066602 for motivation.
- "Remove" better reflects that the issue is being permanently hidden for everybody. With "False Positive" also helping convey what's being flagged to the QA service.
- "Issue" is a little more suitable than "Error" because it has a slightly different meaning which can apply to a wider variety of things (e.g. "Missing Geometry" in ImproveOSM isn't necessarily an error, but could be described as an issue).
- Just removed "Error" from the KeepRight title as this is what's done in iD v3 anyway and works fine in the title spot.
- Removed the `detail_title` key since it isn't used anywhere (made me ponder whether localised string coverage should be tested).
The idea to add information buttons with more …

Update QA button strings

---

modules/core/context.js
modules/core/index.js
modules/core/uploader.js
modules/modes/save.js
modules/ui/commit.js
modules/ui/init.js

Closes #7247.
This adds a `coreUploader` object that handles the saving of changesets separately from mode and UI functionality. In effect, this allows for uploads to be triggered programmatically.

Add upload controller

---

data/deprecated.json

Following a discussion on the tagging mailing list and on the ​wiki, this changes the tag `car=yes/no` on `amenity=charging_station` to` motorcar=yes/no` to be consistent with the tag used for access.

change car=* to motorcar=* on charging_station

---

css/80_app.css

Fixes #10573  where the empty nav button for 'next' was overlapping the keyboard shortcuts button when the user was currently view the Quality Assurance page.

Update help panel navigation buttons
